### ISSUE TITLE
Performance issues with Pytubefix 6.1.1

### ISSUE THREAD

**Issue by NannoSilver** [JuanBindez/pytubefix#100]
I noticed that Pytubefix 6.0 as well as 6.1.1 is slower than version 5.7.

I found that while retrieving video duration, with and without proxy.
This is the code I used:
```
import datetime
from pytubefix import YouTube


youtube_video_url = 'https://www.youtube.com/watch?v=Bfo2xIeaOAE'

# handler for proxy:
# proxy_handler = {'proxy_type': f'https://{user}:{password}@{ip_proxy}:{port}'}

time_before = datetime.datetime.now()

# with proxy:
# duration = YouTube(youtube_video_url, proxies=proxy_handler).length

# without proxy:
duration = YouTube(youtube_video_url).length


required_time = datetime.datetime.now() - time_before

print(f'Duration: {duration} seconds                (Required time to retrieve duration: {required_time.total_seconds()} seconds)')
```

Below is the performance I found. It is the average for a number of tests running in a local computer with Windows 11, pycharm and python 3.9.

**Required time to retrieve video length (video duration):**

With Pytubefix 5.7.0 with the [fix](https://github.com/JuanBindez/pytubefix/issues/93#issuecomment-2218342968):
Without proxy: 0.3 seconds
With proxy: 2.0 seconds

With Pytubefix 6.1.1:
Without proxy: 2.2 seconds
With proxy: 10.0 seconds

With Pytubefix 6.1.1 takes over 5 times more time to retrieve duration than with 5.7.
Anybody else with this issue?

**Comment by felipeucelli** [comment]
Hi @NannoSilver , would you mind testing [this change](https://github.com/felipeucelli/pytubefix/commit/11f219bced1c120f09a213924f6245660830c1dd)?

**Comment by NannoSilver** [comment]
> Hi @NannoSilver , would you mind testing [this change](https://github.com/felipeucelli/pytubefix/commit/11f219bced1c120f09a213924f6245660830c1dd)?

Hi @felipeucelli 
Seems that fixed the problem. Thank you!

**Comment by JuanBindez** [comment]
try v6.1.2

**Comment by NannoSilver** [comment]
Version 6.1.2 fix it.
Thank you @felipeucelli  and @JuanBindez
