### ISSUE TITLE
Clearn File Name

### ISSUE THREAD

**Issue by Tosin-JD** [JuanBindez/pytubefix#102]
When downloading, the file name of the files downloaded sometimes contains special characters like **/** and **\** _(depending on the title of the video on Youtube)_ which is not good for the file system.  
**Suggestion:**  
The special characters should be removed so that the name will be clean and not affect the file system.

**Comment by JuanBindez** [comment]
True, you're right, I inverted these / so that it wouldn't affect you, but it could cause problems, I'll do tests and update the library, thank you very much

**Comment by Tosin-JD** [comment]
Thank you so much for looking into it.

**Comment by Balawoo** [comment]
Hello @JuanBindez 
Thanks for the fantastic job, in the same topic on filename:
Is it possible to have an option that give it with extension?

**Comment by NannoSilver** [comment]
It is possible to choose the file name as well as the extension and destination folder doing this:
```
from pytubefix import YouTube

url = 'https://www.youtube.com/watch?v=ytIUl7V4P9s'

yt = YouTube(url)

stream = yt.streams.get_by_itag(137)
stream.download(output_path='downloaded_videos', filename=f'TheNameOfMyChoice.mp4')

```

**Comment by JuanBindez** [comment]
> Hello @JuanBindez Thanks for the fantastic job, in the same topic on filename: Is it possible to have an option that give it with extension?

If you want to save it as an mp3, just pass the parameter mp3=True like the example below

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "url"
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_audio_only()
ys.download(mp3=True)
```

**Comment by JuanBindez** [comment]
> When downloading, the file name of the files downloaded sometimes contains special characters like **/** and *_*_ _(depending on the title of the video on Youtube)_ which is not good for the file system. **Suggestion:** The special characters should be removed so that the name will be clean and not affect the file system.

Hello, I would like you to test this specific version to see if it is better  -> pip install pytubefix==6.2rc1

**Comment by Balawoo** [comment]
I have a remark, in case of the name of the video contains some characters like "," or ";" we have an error .

I give an example, my script is:

```
def Download(link):
	yt = YouTube(link, on_progress_callback = on_progress)
	youtubeName = yt.streams.get_highest_resolution()
	#caption = youtubeObject. captions.get_by_language_code('en')
	try:
		youtubeName.download(path_to_download)
		#caption.xml_captions
	except:
		print("An error has occurred")
	return yt.title + '.mp4'
```

like the title in case of link = https://www.youtube.com/watch?v=EuDGQEQtevI contains a comma.
The title is : ELECTRONIC BANK STATEMENT TRANSACTION TYPES CREATION, TECHNICAL INTEGRATION
It's not the name of the file **ELECTRONIC BANK STATEMENT TRANSACTION TYPES CREATION TECHNICAL INTEGRATION**

**Comment by JuanBindez** [comment]
> "," or ";"

Generally the characters that cause problems when downloading on some systems are /, :, *, ", <, > and | which now in the next versions pytubefix will remove from the titles to avoid problems, as the ones you mentioned as ", " ";" I believe there are no problems

**Comment by Balawoo** [comment]
> > "," or ";"
> 
> Generally the characters that cause problems when downloading on some systems are /, :, *, ", <, > and | which now in the next versions pytubefix will remove from the titles to avoid problems, as the ones you mentioned as ", " ";" I believe there are no problems

you are right on MacOs there is no problem to save it, my issue (I'm a dummy) it's more one file name, I need to remove from the title, the comma ... Thanks for the great job

**Comment by JuanBindez** [comment]
> > > "," or ";"
> > 
> > 
> > Generally the characters that cause problems when downloading on some systems are /, :, *, ", <, > and | which now in the next versions pytubefix will remove from the titles to avoid problems, as the ones you mentioned as ", " ";" I believe there are no problems
> 
> you are right on MacOs there is no problem to save it, my issue (I'm a dummy) it's more one file name, I need to remove from the title, the comma ... Thanks for the great job

try 

```python
translation_table = str.maketrans({
                ',': '',
                ';': '',
            })
            
title = "ELECTRONIC BANK STATEMENT TRANSACTION TYPES CREATION, TECHNICAL INTEGRATION"

title.translate(translation_table)
```
