### ISSUE TITLE
Differences between pytube 15.0.0 and pytubefix 6.1.2

### ISSUE THREAD

**Issue by deeffest** [JuanBindez/pytubefix#104]
Example code:
```
from pytube import YouTube

yt = YouTube("https://music.youtube.com/watch?v=WFEEGzqVM7U")
print(f"Author: {yt.author}\nThumbnail: {yt.thumbnail_url}")
```
When I want to get the author of a video or video thumbnail, I get this in pytube:
```
Author: danjerr
Thumbnail: https://lh3.googleusercontent.com/ja9omfYv7t4S1z-h1qz1un-gchIo59Psjos2K3O543rZEjGm8oyfQDoVJK-V7Nq0JXIG7x2f4thnutEw=w544-h544-l90-rj
```
In pytubefix, however, I get this:
```
Author: danjerr - Topic
Thumbnail: https://i.ytimg.com/vi/WFEEGzqVM7U/sddefault.jpg
```
In my opinion pytube has a slightly nicer result and I don't understand why it looks different in pytubefix. maybe the pytube method has some disadvantages? I would be grateful for an answer.

**Comment by felipeucelli** [comment]
Pytube is defaulting to the **ANDROID_MUSIC** client which has some limitations, while pytubefix uses **ANDROID_TESTSUITE** which has a similar structure to ANDROID.

You can get the same result as in pytube just by changing the client:

```python
yt = YouTube("https://music.youtube.com/watch?v=WFEEGzqVM7U", 'ANDROID_MUSIC')
print(f"Author: {yt.author}\nThumbnail: {yt.thumbnail_url}")
```
