### ISSUE TITLE
Can't download age restricted videos

### ISSUE THREAD

**Issue by GordonQuick** [JuanBindez/pytubefix#108]
**Describe the bug**
Age restricted videos can't be downloaded. Even when using oauth

**To Reproduce**
1. Try to download https://www.youtube.com/watch?v=KU5oMbX7m38

without auth
```
from pytubefix import Playlist
from pytubefix import YouTube
from pytubefix.cli import on_progress


p = Playlist('https://www.youtube.com/playlist?list=PLmZJ1ohwjt2O6qMwMFCRJMR_SnwyKFfvL')

print(f'Downloading: {p.title}')
for video in p.videos:
    video.streams.first().download(r'G:\test')
```

or with auth

```
from pytubefix import Playlist
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = input("url >")

yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()
```

3. See error

Traceback (most recent call last):
  File "c:\Users\Gord\Python\playlistdownloader.py", line 10, in <module>
    video.streams.first().download(r'G:\test')
    ^^^^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", 
line 501, in streams
    self.check_availability()
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", 
line 282, in check_availability
    raise exceptions.AgeRestrictedError(video_id=self.video_id)
pytubefix.exceptions.AgeRestrictedError: Video ID = KU5oMbX7m38: is age restricted, and can't be accessed 
without logging in.

**Expected behavior**
Either download without problem or working authentication

**Comment by JuanBindez** [comment]
Hello, I ask you to test this version pip install pytubefix==6.3rc1 which is currently being tested by @felipeucelli in #111, before testing read the commit carefully

**Comment by GordonQuick** [comment]
> Hello, I ask you to test this version pip install pytubefix==6.3rc1 which is currently being tested by @felipeucelli in #111, before testing read the commit carefully

I don't get the option to authenticate.

```
  File "c:\Users\Gord\Python\playlistdownloader.py", line 17, in <module>
    ys = yt.streams.get_highest_resolution()
         ^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 543, in streams
    self.check_availability()
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 291, in check_availability
    self.age_check()
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 360, in age_check
    raise exceptions.AgeCheckRequiredAccountError(self.video_id)
pytubefix.exceptions.AgeCheckRequiredAccountError: Video ID = KU5oMbX7m38: Sorry, something is wrong. This video may be inappropriate for some users. Sign in to your primary account to confirm your age.
```

Is there something wrong with this auth code?

```
from pytubefix import Playlist
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = input("url >")

yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()
```

**Comment by felipeucelli** [comment]
This error usually occurs when using a brand account, for example YouTube. Test using the primary account and tell us the result.

**Comment by GordonQuick** [comment]
> This error usually occurs when using a brand account, for example YouTube. Test using the primary account and tell us the result.

How do I delete the cookies/cache so I can reauthenticate? I don't get the option to authenticate anymore.

**Comment by felipeucelli** [comment]
> How do I delete the cookies/cache so I can reauthenticate? I don't get the option to authenticate anymore.

Inside the pytubefix project folder, you will find a **__ cache __** folder, just delete it.

In the future I think about adding a delete parameter.

**Comment by GordonQuick** [comment]
> > How do I delete the cookies/cache so I can reauthenticate? I don't get the option to authenticate anymore.
> 
> Inside the pytubefix project folder, you will find a **__ cache __** folder, just delete it.
> 
> In the future I think about adding a delete parameter.

yes it works now for single videos, thanks. 

How do I use oauth in a playlist download as "playlist" can't use the argument use_auth. This is my regular code:

```
from pytubefix import Playlist
from pytubefix import YouTube
from pytubefix.cli import on_progress


p = Playlist('URL')

print(f'Downloading: {p.title}')
for video in p.videos:
    video.streams.first().download(r'G:\test')
```

If I just add the arguments after URL I get this error:

```
Traceback (most recent call last):
  File "c:\Users\Gord\Python\playlistdownloader.py", line 6, in <module>
    p = Playlist('https://www.youtube.com/playlist?list=PLmZJ1ohwjt2O6qMwMFCRJMR_SnwyKFfvL', use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Playlist.__init__() got an unexpected keyword argument 'use_oauth'
```

**Comment by JuanBindez** [comment]
try v6.3rc2

**Comment by GordonQuick** [comment]
> try v6.3rc2

same result as https://github.com/JuanBindez/pytubefix/issues/108#issuecomment-2233316632

**Comment by felipeucelli** [comment]
Try:

```python
from pytubefix import Playlist
from pytubefix import YouTube
from pytubefix.cli import on_progress


p = Playlist('URL')

print(f'Downloading: {p.title}')
for video in p.video_urls:
    YouTube(video, use_oauth=True).streams.first().download(r'G:\test')
```
