### ISSUE TITLE
 "Video unavailable" for unknown reason with oauth

### ISSUE THREAD

**Issue by zkreutzjanz** [JuanBindez/pytubefix#110]
**Describe the bug**
Getting "Video unavailable" for unknown reason.
```"\u001b[91m---ZOY1kzAc is unavailable\u001b[0m"```

**To Reproduce**
1. yt = YouTube(f"https://www.youtube.com/watch?v={video_id}",use_oauth=True, allow_oauth_cache=True)
2. Get this printed: 
```The ANDROID_TESTSUITE client did not get a valid response, trying to use the WEB client.
Video ID: ---ZOY1kzAc
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide this log output.
```

**Desktop (please complete the following information):**
 - Pytubefix Version 6.2.2

**Comment by JuanBindez** [comment]
Hello, I ask you to test this version pip install pytubefix==6.3rc1 which is currently being tested by @felipeucelli in #111, before testing read the commit carefully

**Comment by zkreutzjanz** [comment]
Thank you! The error to the console is now fixed, but there is something else. 
```yt.streams.get_by_itag(402)```
Will throw "---ZOY1kzAc is unavailable" when oauthed.
I am not sure if get_by_itag is supposed to fail like this.

**Comment by zkreutzjanz** [comment]
Update. I think the account I was using was banned. 
Tried with a new account and get this error: 'HTTP Error 428: Precondition Required'

**Comment by felipeucelli** [comment]
> Thank you! The error to the console is now fixed, but there is something else. `yt.streams.get_by_itag(402)` Will throw "---ZOY1kzAc is unavailable" when oauthed. I am not sure if get_by_itag is supposed to fail like this.
> 
> Edit: And it does work when not oauthed.

For me, this video is working correctly, perhaps there is some regional blocking.


> Update. I think the account I was using was banned. Tried with a new account and get this error: 'HTTP Error 428: Precondition Required'


This error usually refers to session token expiration.

**Comment by zkreutzjanz** [comment]
Huh, now no auth is getting these errors on the new update.
![image](https://github.com/user-attachments/assets/23f7c5d9-d316-44c3-815c-94416b79b5b7)

**Comment by zkreutzjanz** [comment]
@JuanBindez I am working on a fix, will have a pull request for you in by tonight.
