### ISSUE TITLE
What type of errors should we throw - developer decisions

### ISSUE THREAD

**Issue by zkreutzjanz** [JuanBindez/pytubefix#116]
@JuanBindez and @felipeucelli 

The exceptions already in pytube are relatively broad. We need to decide what exception categories we want to throw. 
I am finding new error reasons by the day, and new exceptions for each is a bloated.

See below, I just found a new error reason:
```   elif status == 'ERROR':
                if reason == 'Video unavailable':
                    raise exceptions.VideoUnavailable(video_id=self.video_id)
                elif reason == 'This video is private':
                    raise exceptions.VideoPrivate(video_id=self.video_id)
                elif reason == 'This video is unavailable':
                    raise exceptions.VideoUnavailable(video_id=self.video_id)
                **elif reason == 'This video has been removed by the uploader':
                    raise exceptions.VideoUnavailable(video_id=self.video_id)**
                elif reason == 'This video is no longer available because the YouTube account associated with this video has been terminated.':
                    raise exceptions.VideoOwnerDeleted(video_id=self.video_id)
```

To go about this we need to think what errors actually matter to users. We also should maintain most backwards compatibility

# Proposal
The major errors should be these:

- VideoPrivate (useful for users to know this)
- MembersOnly (useful for users to know this)
- VideoRegionBlocked (useful for users to know this)
- UnhandledError (new class, anything that throws this also prompts user to report bug)
- VideoUnavailable (The catch-all class, almost every new reason we find should go here)

I think we need to keep these three separate for backwards compatibility, otherwise I would make into two seperate ones:
- AgeRestrictedError
- AgeCheckRequiredError
- AgeCheckRequiredAccountError

And the naming on these is not ideal, but should keep for backwards compatibility for livestreams:
- LiveStreamError
- RecordingUnavailable

So, that would mean removing "StreamingDataMissing" and "VideoOwnerDeleted" which were just added.

And from now on, we add most newly found errors to "VideoUnavailable" unless there is some really important reason for user to know the error type.

Please respond if these changes make sense, and I will get a PR in.

**Comment by JuanBindez** [comment]
Hello, you can decide too, help us because we are always able to do all the parts, so it is important that everyone who can help, do the PR, and we will carry out the tests, and we will adjust as needed.

**Comment by JuanBindez** [comment]
I'm going to do it like this, I'm going to open a new branch, with the name "exceptions" and we're going to deal with these errors there until it's more stable to merge, then when they do PR related to these exceptions I'll transfer them to this branch.
