### ISSUE TITLE
pytubefix.exceptions.LoginRequired: xGT7nrDNnf8 requires login to view

### ISSUE THREAD

**Issue by kof0012** [JuanBindez/pytubefix#126]
**Describe the bug**
It is normal for me to download videos on my local computer, but when I put the code on the server, downloading the video list fails with a prompt that I have not logged in. Why is this? 【pytubefix.exceptions.LoginRequired:】

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Python Version [3.10.2]
 - Pytubefix Version [1.6.5]

**Comment by JuanBindez** [comment]
- > #119

update your pytubefix to 6.5.1

**Comment by kof0012** [comment]
Thank you for your reply. I wrote the wrong version number, I am using the latest version. I guess my IP has been banned.
