### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by Hoshinaku** [JuanBindez/pytubefix#129]
i tried another solutions but nothing works, code just frizzing when it trying download something
code i used:

from pytubefix import YouTube

yt = YouTube("https://www.youtube.com/watch?v=xxxxxxxxxx", use_oauth=True, allow_oauth_cache=False)

stream = yt.streams.filter(only_audio=True).first()
stream.download(output_path="audios/", filename=f"1.mp3")

it only creating 0 bytes file and frozzing, pls help

**Comment by anAwesomeWave** [comment]
Same issue using the latest version. How can I solve it?
