### ISSUE TITLE
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by in4sec-org** [JuanBindez/pytubefix#133]
![Screenshot from 2024-07-25 12-54-13](https://github.com/user-attachments/assets/e9a7f556-a42a-4cc2-9705-d47aa09d215c)

**Comment by Tanmaypatil123** [comment]
facing the same issue

**Comment by kettenbach-it** [comment]
Same here

**Comment by JuanBindez** [comment]
Is this in the latest version of pytubefix?

**Comment by kettenbach-it** [comment]
For me the latest pytubefix fixed it
