### ISSUE TITLE
yt.publish_date returning blank value

### ISSUE THREAD

**Issue by Concept211** [JuanBindez/pytubefix#138]
I'm currently running the latest version (6.6.2) but now any videos that I try to process, the yt.publish_date property always returns a blank value instead of the datetime object as before. I'm also using oauth if that makes any difference.

**Comment by JuanBindez** [comment]
update to the latest version and test, show us the code you are using to test

**Comment by Concept211** [comment]
Upgraded to **pytubefix 6.8.1**

Ran code:
```
yt = YouTube("https://www.youtube.com/watch?v=YL9apblSQ-s", use_oauth=True, allow_oauth_cache=True)
print(yt.publish_date)
```

Output:
`None`

**Comment by JuanBindez** [comment]
I just used it without authentication

and it worked normally:

```python
>>> from pytubefix import YouTube
>>> 
>>> yt = YouTube("https://www.youtube.com/watch?v=YL9apblSQ-s")
>>> print(yt.publish_date)
2024-07-14 09:00:17-07:00
>>> 

```

**Comment by Concept211** [comment]
So strange. Even without authentication I still get "None".

Is there a way to print the raw output to see all the data that is being returned from the query? All other properties seem to load fine except for the publish_date.

Also, I'm running my application on a VPS physically located in Germany. Not sure if geographically there are any differences in what YouTube returns.

**Comment by NannoSilver** [comment]
I tested here also, without authentication, with pytubefix 6.8.1, and it works normally.


```
from pytubefix import YouTube

yt = YouTube("https://www.youtube.com/watch?v=m2caY5CL63E")
print(yt.publish_date)
```

output:
`2024-07-23 08:00:54-07:00`


Maybe the IP of your VPS was blocked by Youtube.
If you do many requests, likely will be blocked. To overcome the blocking you have to use proxies.

**Comment by Concept211** [comment]
For whatever reason, the HTML output comes through different just for the date value. I updated your **publish_date** function within the **extract.py** file to properly handle both versions and now it works perfectly...

```
def publish_date(watch_html: str):
    """Extract publish date and return it as a datetime object
    :param str watch_html:
        The html contents of the watch page.
    :rtype: datetime
    :returns:
        Publish date of the video as a datetime object with timezone.
    """
    try:
        # First attempt to find "datePublished"
        result = re.search(
            r'(?<=itemprop="datePublished" content=")\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}',
            watch_html
        )
        if result:
            return datetime.fromisoformat(result.group(0))

        # If "datePublished" is not found, attempt to find "publishDate"
        result = re.search(
            r'(?<="publishDate":{"simpleText":")\w+ \d{1,2}, \d{4}',
            watch_html
        )
        if result:
            return datetime.strptime(result.group(0), '%b %d, %Y')
    except AttributeError:
        return None
```
