### ISSUE TITLE
generate_srt_captions is not working 

### ISSUE THREAD

**Issue by BinSlayer01** [JuanBindez/pytubefix#14]
I'm using your pytubefix and testing the captions with this youtube video: https://www.youtube.com/watch?v=AbyJignbSj0&ab_channel=ParamountPictures

I'm doing this `print(caption.generate_srt_captions())`  and it's not printing anything. xml_captions works but not generate_srt_captions Any idea what I could be doing wrong please?

full code:
```

from pytubefix import YouTube
yt = YouTube("https://www.youtube.com/watch?v=AbyJignbSj0")
yt.bypass_age_gate()
caption = yt.captions['en-US']
print(caption.generate_srt_captions())
```

**Comment by BinSlayer01** [comment]
issue has been resolved, thank you very much

**Comment by JuanBindez** [comment]
Version  with  the fix released ->  https://pypi.org/project/pytubefix/1.8.3/
