### ISSUE TITLE
Just tested the latest release, it works great!

### ISSUE THREAD

**Issue by dvaldivia** [JuanBindez/pytubefix#141]
that's it! that's the bug hahaha

**Comment by JuanBindez** [comment]
> that's it! that's the bug hahaha

It looks like pytube, right? hahaha

**Comment by dvaldivia** [comment]
yeah, just replaced the import!

**Comment by JuanBindez** [comment]
after a look, we are maintaining compatibility with the pytube api, but there are also some new features
