### ISSUE TITLE
UnknownVideoError :  This live event has ended.

### ISSUE THREAD

**Issue by jaferrando** [JuanBindez/pytubefix#150]
**Describe the bug**
Can't download a video from a past live event.

**To Reproduce**

```
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://youtu.be/qyltRTowCBY"
 
yt = YouTube(url)
print(yt.title)
 
ys = yt.streams.get_audio_only()
ys.download(mp3=True) # pass the parameter mp3=True to save in .mp3
```

**Expected behavior**
Download the video

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.11
 - Pytubefix Version pytubefix-6.8.1

**Comment by JuanBindez** [comment]
no error appeared?

**Comment by NannoSilver** [comment]
After the live ends, it does not become available to download immediately, but only after a few hours or, in rare cases, after a few days.

**Comment by JuanBindez** [comment]
I just used the same code and it worked perfectly, it downloaded completely

**Comment by jaferrando** [comment]
Thanks for the help.
For future reference, this particular event had ended a little more than 24 hours before my last attempt and a little more than 26 hours before @JuanBindez successfully downloaded the stream.

**Comment by jaferrando** [comment]
The error was:

Jam Oviedo 2.0 31-7-2024 Javi Queen
Unknown Video Error
Video ID: qyltRTowCBY
Status: OK
Reason: This live event has ended.
Developer Message: Unknown video status
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide the above log output.
Traceback (most recent call last):
  File "C:\Users\jalvarezferr\yt.py", line 9, in <module>
    ys = yt.streams.get_audio_only()
         ^^^^^^^^^^
  File "C:\Users\jalvarezferr\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 552, in streams
    self.check_availability()
  File "C:\Users\jalvarezferr\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 336, in check_availability
    raise exceptions.UnknownVideoError(video_id=self.video_id, status=status, reason=reason, developer_message=f'Unknown video status')
pytubefix.exceptions.UnknownVideoError: ←[91mqyltRTowCBY has an unknown error, check logs for more info←[0m
