### ISSUE TITLE
Tor routing for Pytubefix

### ISSUE THREAD

**Issue by sleepingcat4** [JuanBindez/pytubefix#156]
An essential fix I was thinking for the problem while trying to download large amounts of data from YouTube: YouTube blocks/limits the IP address after a certain period. I was suggesting if there could be a way, where TOR network routing could be included inside Pytube fix so that YouTube can't possibly flag the actual IP address and since TOR provides option to change the intermediate nodes and guard node protects the actual IP, it can be a way to get rid of the IP limiting problem posed by YouTube

**Comment by NannoSilver** [comment]
I did not tested, but is likely route thru TOR is already possible by setting pytubefix to use proxy, and setting as proxy the localhost IP at port 9150, that is the port Tor Browser listen.
