### ISSUE TITLE
Please open https://www.google.com/device and input code NGY-GKK-CBWC Press enter when you have completed this step.

### ISSUE THREAD

**Issue by Morteza820** [JuanBindez/pytubefix#160]
i got this bug now

Please open https://www.google.com/device and input code NGY-GKK-CBWC
Press enter when you have completed this step.

**Comment by JuanBindez** [comment]
This is not a bug, it's just that you have to do this step by step to be able to do what you want

**Comment by Morteza820** [comment]
this is my code:

elif text.startswith(".mus "):
    try:
        name = text.replace(".mus ", "")
        yt = YouTube(name, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
        print(yt.title)
        ys = yt.streams.get_audio_only()
        ys.download(mp3=True) # pass the parameter mp3=True to save in .mp3
        print("done")
    except Exception as er:
        print(er)

**Comment by JuanBindez** [comment]
You need to open that link that appears and enter the code, after entering the code, return to the terminal and press enter

**Comment by Morteza820** [comment]
I dont understand

**Comment by Morteza820** [comment]
> You need to open that link that appears and enter the code, after entering the code, return to the terminal and press enter

can you help more please?

**Comment by JuanBindez** [comment]
yes of course

**Comment by JuanBindez** [comment]
There is a link that appears right?

**Comment by JuanBindez** [comment]
https://www.google.com/device

**Comment by Morteza820** [comment]
> There is a link that appears right?

yes

**Comment by JuanBindez** [comment]
You need to click on this link, it will open in the browser


something like this will appear in the terminal:  

input code NGY-GKK-CBWC

You copy this code and paste it on the page you opened in the browser and enter in the browser and in the terminal

**Comment by Morteza820** [comment]
> You need to click on this link, it will open in the browser
> 
> something like this will appear in the terminal:
> 
> input code NGY-GKK-CBWC
> 
> You copy this code and paste it on the page you opened in the browser and enter in the browser and in the terminal

I did , thanks... how to send music in chat? can you complete the code above?
