### ISSUE TITLE
Download videos in 360p

### ISSUE THREAD

**Issue by nathannogueira** [JuanBindez/pytubefix#164]
Hello, get_highest_resolution() is not downloading videos in the highest available resolution (e.g., 720p, 1080p, etc.). Instead, the downloaded videos are being saved in 360p, even when higher resolutions are available in MP4 format.

**Comment by NannoSilver** [comment]
Not a bug. This has been discussed recently. Search for the "closed" issues. Youtube changed on its side. 
Start searching here: https://github.com/JuanBindez/pytubefix/issues/145
