### ISSUE TITLE
Auth in Docker

### ISSUE THREAD

**Issue by Mak5er** [JuanBindez/pytubefix#165]
I use PytubeFix in docker container and i can not complete auth.

**Comment by snoop088** [comment]
I use it in AWS Lambda and again I can't complete manual auth. Did Youtube change anything, as this lib was working flawlessly last week or so.

**Comment by pixmatic** [comment]
Same problem. Now I can't use my app in Lambda. I use oauth2 to authenticate with Youtube API with google_auth_oauthlib.flow and google.oauth2.credentials. It would be nice if I could use my credentials with pytubefix.

**Comment by benqbed** [comment]
Im getting an error that might be related:

**Comment by JuanBindez** [comment]
hello, test this pre-release version pip install pytubefix==6.13rc1 and do the tests if you have any questions, see here #190

**Comment by Mak5er** [comment]
All working fine. Thanks
