### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by Mostafa-Mohamed-Atef** [JuanBindez/pytubefix#177]
**Describe the bug**
I tried downloading videos from youtube only 360p are available as the highest resolution, tried filtering by resolution and progressive=False but it downloads broken videos

**Code**
def download():
    global progress_bar
    try:
       yd = yt.streams.get_highest_resolution()
       print(yt.title)
       print(yd)
       progress_bar = tqdm(total=yd.filesize, unit='0', unit_scale=True, desc="Downloading")
       yd.download(path)
       progress_bar.close()
       print('completed')
    except Exception as e:
        print(e)

**output**
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="24fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">

**note**
I updated the last pytubefix version + I'm on linux (if it is important)

**Comment by felipeucelli** [comment]
YouTube changed streams internally, see #128.

**Comment by Mostafa-Mohamed-Atef** [comment]
it worked thanks
