### ISSUE TITLE
get_highest_resolution() doesn't work

### ISSUE THREAD

**Issue by greizdeifi** [JuanBindez/pytubefix#186]
The get_highest_resolution() doesn't work properly and always delivers the 360p stream and all YouTube videos I've tried.
Also get_lowest_resolution() always delivers the 360p stream. Also in the terminal the default download is 360p.

**To Reproduce**
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = input("URL >")

yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
print(yt.streams)

ys = yt.streams.get_highest_resolution()
print(ys)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Python Version [3.11.5]
 - Pytubefix Version [6.11.0]

**Comment by felipeucelli** [comment]
YouTube changed streams internally, see https://github.com/JuanBindez/pytubefix/issues/128.
