### ISSUE TITLE
Some StreamQuery Objects Returning 'None' From get_highest_resolution() method

### ISSUE THREAD

**Issue by modey3** [JuanBindez/pytubefix#188]
**Describe the bug**
As title says. I'm trying to download the following url:
https://www.youtube.com/watch?v=iiy2u3Ky4u4

**To Reproduce**
Run the following code:
from pytubefix import YouTube
from pytubefix.cli import on_progress
 url = "https://www.youtube.com/watch?v=iiy2u3Ky4u4"
 yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
 ys = yt.streams.get_highest_resolution()
ys.download() # you will only get the request to authenticate once you download

**Expected behavior**video download

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Python Version3.10.11
 - Pytubefix Version [6.9.2]

**Additional context**
StreamQuery Data:
[<Stream: itag="146" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.640028" progressive="False" type="video">, <Stream: itag="145" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="224" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="144" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="222" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="223" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="143" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="142" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d400d" progressive="False" type="video">, <Stream: itag="161" mime_type="video/mp4" res="None" fps="24fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="148" mime_type="audio/mp4" abr="None" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="149" mime_type="audio/mp4" abr="None" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="150" mime_type="audio/mp4" abr="None" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="259" mime_type="audio/mp4" abr="None" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="261" mime_type="audio/mp4" abr="None" acodec="mp4a.40.2" progressive="False" type="audio">]

**Comment by modey3** [comment]
Here is the StreamQuery Data from a video that works:
`<Stream: itag="18" mime_type="video/mp4" res="360p" fps="25fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="25fps" vcodec="avc1.640028" progressive="False" type="video">
<Stream: itag="248" mime_type="video/webm" res="1080p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="399" mime_type="video/mp4" res="1080p" fps="25fps" vcodec="av01.0.08M.08" progressive="False" type="video">
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="25fps" vcodec="avc1.4d401f" progressive="False" type="video">
<Stream: itag="247" mime_type="video/webm" res="720p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="398" mime_type="video/mp4" res="720p" fps="25fps" vcodec="av01.0.05M.08" progressive="False" type="video">
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="25fps" vcodec="avc1.4d401e" progressive="False" type="video">
<Stream: itag="244" mime_type="video/webm" res="480p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="397" mime_type="video/mp4" res="480p" fps="25fps" vcodec="av01.0.04M.08" progressive="False" type="video">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="25fps" vcodec="avc1.4d401e" progressive="False" type="video">
<Stream: itag="243" mime_type="video/webm" res="360p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="396" mime_type="video/mp4" res="360p" fps="25fps" vcodec="av01.0.01M.08" progressive="False" type="video">
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="25fps" vcodec="avc1.4d4015" progressive="False" type="video">
<Stream: itag="242" mime_type="video/webm" res="240p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="395" mime_type="video/mp4" res="240p" fps="25fps" vcodec="av01.0.00M.08" progressive="False" type="video">
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="25fps" vcodec="avc1.4d400c" progressive="False" type="video">
<Stream: itag="278" mime_type="video/webm" res="144p" fps="25fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="394" mime_type="video/mp4" res="144p" fps="25fps" vcodec="av01.0.00M.08" progressive="False" type="video">
<Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">
<Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">
<Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">
<Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">`

The video that is giving me trouble is apart of a subscription service. I'm logged into YT using my credentials do YT should be receiving my access token. Would subscription services have separate tokens?

**Comment by jhanley-com** [comment]
NOT A BUG

The video that you reference is not publicly available. YouTube supports videos that require subscriptions, payments or watching advertisements. Your example requires a subscription to Paramount+

Solution: Subscribe to Paramount+ and then authorize using your account credentials.
