### ISSUE TITLE
chapter and key moments        #enhancement

### ISSUE THREAD

**Issue by JedlikOne** [JuanBindez/pytubefix#19]
Hello I do not know how to make make it part of your repo, but I have made two functions that returns chapters and keymoments from video.

[ChaptersAndKeyMoments.zip](https://github.com/JuanBindez/pytubefix/files/13479131/ChaptersAndKeyMoments.zip)

Jan

**Comment by JuanBindez** [comment]
> Hello I do not know how to make make it part of your repo, but I have made two functions that returns chapters and keymoments from video.
> 
> [ChaptersAndKeyMoments.zip](https://github.com/JuanBindez/pytubefix/files/13479131/ChaptersAndKeyMoments.zip)
> 
> Jan

Hi JedlikOne, thanks for contributing to this project, I'll try to incorporate your creation soon!

**Comment by JuanBindez** [comment]
https://pytubefix.readthedocs.io/en/latest/user/chapters.html
