### ISSUE TITLE
pytubefix.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

### ISSUE THREAD

**Issue by brianwang0413** [JuanBindez/pytubefix#194]
I got a problem when I use pytubefix
![image](https://github.com/user-attachments/assets/a1b1ac1c-ba7a-4499-9aa8-a29e5915bc47)

**Comment by JuanBindez** [comment]
This is being closed due to lack of information!
