### ISSUE TITLE
on_progres doesn't work fully

### ISSUE THREAD

**Issue by NeUk1N** [JuanBindez/pytubefix#197]
__________
My progress bar is displayed with a delay, and when it appears, it is either with 100% or another large value. 

__________
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://www.youtube.com/watch?v=25N1pdzvp4c"

yt = YouTube(url, on_progress_callback = on_progress)
           
ys = yt.streams.get_highest_resolution()

ys.download()
__________
When you start the program, a progress bar immediately appears with 0%, gradually filling up to 100%.
__________

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Python Version [3.9.6]
 - Pytubefix Version [15.0.0]

__________
Is it because I am using a proxy server when downloading?

**Comment by jhanley-com** [comment]
Insufficient information to debug.

I verified that the on_progress_callback works correctly on Windows 10 x64 today with PyTubeFix version 6.16.3.

I have been developing constantly for several months. I have never noticed a problem on Ubuntu or Windows. I suspect you have an issue with your code, but you did not include code to review that implements on_progress().
