### ISSUE TITLE
Getting request error 

### ISSUE THREAD

**Issue by viper7BG** [JuanBindez/pytubefix#203]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
Im getting an error while trying to download any kind of youtube videos

ERROR: This request has been detected as a bot, please try again or log in to view

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = "https://youtu.be/JNHUHaUwk-M?si=gWCyQRuW1A_rhEub"

yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()

```

__________
**Expected behavior**

__________
**Screenshots**
https://prnt.sc/ektTNmSmOW1Q

__________
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.8.10
 - Pytubefix Version 6.13.1

__________
**Additional context**

**Comment by JuanBindez** [comment]
see #170
