### ISSUE TITLE
Support for Downloading 1080p+ Videos with Audio

### ISSUE THREAD

**Issue by theankitjais** [JuanBindez/pytubefix#205]
Could you add support for downloading 1080p or higher videos with audio in a single step? Currently, I have to download video and audio separately and then merge them using FFmpeg, which adds complexity.

Adding this feature would streamline the process and improve the user experience, especially for those who aren't familiar with FFmpeg.

Thanks for considering this request!

**Comment by theankitjais** [comment]
@JuanBindez Can you please look into it?

**Comment by NannoSilver** [comment]
> @JuanBindez Can you please look into it?

This has been answered multiple times. Search the closed issues.
It is a change on Youtube side.
