### ISSUE TITLE
Feature Request: Add Proxy Support for Cloud Environment Compatibility

### ISSUE THREAD

**Issue by serdarildercaglar** [JuanBindez/pytubefix#206]
Hello,

Thank you for developing pytubefix! I have been using this library to download videos from YouTube, and it works great in local environments. However, when attempting to use pytubefix in cloud environments (e.g., AWS, GCP, Azure), the downloads fail due to YouTube's restrictions on cloud-based access. This issue significantly limits the usability of the library for automated, cloud-based workflows.

Feature Request:

To address this limitation, I am requesting the addition of proxy support to the pytubefix library. By allowing users to configure a proxy server, we can bypass YouTube's restrictions on cloud access and enable video downloads from cloud environments. This feature would be precious for those of us who need to automate YouTube video downloads as part of cloud-based applications.

Proposed Solution:

Introduce a new parameter in the YouTube, Playlist, and Channel classes to accept proxy settings (e.g., proxy_url, proxy_port).
Allow the proxy settings to be used for all HTTP requests made by the library.
Include an option to enable/disable proxy use easily.
Benefits:

Enables pytubefix to work in cloud environments where direct YouTube access is restricted.
Expands the library's use cases for cloud automation and large-scale video processing tasks.
Provides users with more control over their network settings.
Thank you for considering this feature request. Your support for adding proxy functionality would greatly enhance the versatility and utility of pytubefix in various deployment scenarios.

Best regards,

**Comment by NannoSilver** [comment]
Proxy feature already is available. Check the documentation.

**Comment by serdarildercaglar** [comment]
> Proxy feature already is available. Check the documentation.

Sorry, But I couldn't find proxy support in the docs.
