### ISSUE TITLE
While using the pytubefix library on AWS EC2 it shows the Error  'This request has been detected as a bot'

### ISSUE THREAD

**Issue by Buddy4toBuddy** [JuanBindez/pytubefix#208]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
if I used the code on the AWS Ec2 instance when I hit the code it threw the error
"TlB_eWDSMt4 This request has been detected as a bot, please try again or log in to view"
here TlB_eWDSMt4 is the youtube URL ID.

But it works perfectly on my local through the container and without a container.

__________
**code that was used that resulted in the bug**
Here is my code
************************
```python
from pytubefix import YouTube

def fetch_youtube_details(url):
    try:
        yt = YouTube(url)
        details = {
            'title': yt.title,
            'author': yt.author,
            'views': yt.views,
            'thumbnail_url': yt.thumbnail_url,
            'description': yt.description,
            'publish_date': yt.publish_date,
            'length': yt.length
        }
        print('Video details:', details)
    except Exception as e:
        print('Error fetching video details:', e)

url = 'https://www.youtube.com/watch?v=TlB_eWDSMt4'
fetch_youtube_details(url)

```
__________
**Expected behavior**

__________
**Screenshots**

![image](https://github.com/user-attachments/assets/81ff6edf-a001-4910-a826-f4583db816fa)

__________
**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Python Version 3.8.10
 - Pytubefix Version 6.5.1

__________
**Additional context**

**Comment by deconasser** [comment]
Same error happened for me !

**Comment by JuanBindez** [comment]
use the latest version 6.14.0 and see #170

**Comment by bajiegegememeda123** [comment]
YouTube(url, use_oauth=True)

**Comment by felipeucelli** [comment]
Test this PR #209 .

**Comment by 1247862674** [comment]
I have the same error, and I'm also deployed on AWS EC2

**Comment by JuanBindez** [comment]
> I have the same error, and I'm also deployed on AWS EC2

Have you tried with proxy?

**Comment by NannoSilver** [comment]
> I have the same error, and I'm also deployed on AWS EC2

Have to use proxies.
There is no other solution for now.

**Comment by 1247862674** [comment]
> > I have the same error, and I'm also deployed on AWS EC2
> 
> Have you tried with proxy?

Haven’t used an agent yet

**Comment by yannickErp** [comment]
> Have to use proxies. There is no other solution for now.

Anyone know where to find proxies? Paid ones are really expensive with a few dollars per GB, which is deadly for youtube downloads...

**Comment by arkaydeus** [comment]
In addition, most of the paid proxies don't actually work as they've also been flagged as for bot use.
