### ISSUE TITLE
streams.py bug

### ISSUE THREAD

**Issue by bajiegegememeda123** [JuanBindez/pytubefix#210]
streams.py

Source code：
class Stream:
        if 'width' in stream:
            self.width = stream["width"]
        if 'height' in stream:
            self.width = stream["height"]

Correct code：
class Stream:
        if 'width' in stream:
            self.width = stream["width"]
        if 'height' in stream:
            self.height = stream["height"]

**Comment by JuanBindez** [comment]
due to lack of information this will be closed

**Comment by bajiegegememeda123** [comment]
I want to get the width and height of the video stream. Currently, the video stream only has the width property

**Comment by felipeucelli** [comment]
The fix is ​​now available in version 6.15.4.
