### ISSUE TITLE
[Questio] Is it possible to get youtube urls from a certain channel for a certain period of time ?

### ISSUE THREAD

**Issue by timtensor** [JuanBindez/pytubefix#211]
Hi, 
I am interested in finding youtube urls published on a certain week number. Is it possible to list all the youtube urls for a certain week number from pytube fix ?
T

**Comment by felipeucelli** [comment]
Hello, YouTube API provides us videos by pagination of around 30 items. They are provided from newest to oldest.

I don't know of any official way to obtain a specific date, what we can do is get all the videos and filter them by date.
