### ISSUE TITLE
can't download live video that finished streaming few hours ago

### ISSUE THREAD

**Issue by paichiwo** [JuanBindez/pytubefix#212]
__________
**Describe the bug**

Tried to download a video that was streaming live today, but live stream ended few hours ago.

Unknown Video Error
Video ID: Q1lFwLnG0uY
Status: OK
Reason: This live event has ended.
Developer Message: Unknown video status
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide the above log output.
__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

    def download(self):
        output_path = load_settings()
        for i, link in enumerate(self.url_list):
            yt = YouTube(link, on_progress_callback=self.progress_callback)
            if self.dl_format == 'audio':
                yt_stream = yt.streams.get_audio_only()
                filename = handle_audio_extension(yt_stream)
            else:
                yt_stream = yt.streams.get_highest_resolution()
                filename = yt_stream.title + '.mp4'
            self.info_msg(INFO_MSG['downloading'])

            try:
                if os.path.exists(os.path.join(load_settings(), filename)):
                    self.table.frames[i].change_delete_btn()
                    self.info_msg(INFO_MSG['file_exists'])
                else:
                    yt_stream.download(output_path=output_path, filename=filename)
                    self.dl_speed.configure(text=self.initial_speed)
                    self.info_msg(INFO_MSG['dl_complete'])
            except (PermissionError, RuntimeError):
                self.info_msg(INFO_MSG['permission_err'])

```
__________
**Desktop (please complete the following information):**
 - OS: WIN 11
 - Python Version [3.12]
 - Pytubefix Version [6.8.1]

**Comment by NannoSilver** [comment]
Lives only are available for download a while after it finish. "While" may means a few hours or, in rare cases, a few days. It is the time Youtube needs to process the file.
Try again tomorrow.
