### ISSUE TITLE
small bug 

### ISSUE THREAD

**Issue by Sami-000** [JuanBindez/pytubefix#213]
hi man
i installed pytubefix with "pip install pytubefix"
but we have bug here

in pytubefix/extract.py", line 443      
logger.debug(f'Applying po_token to itag={stream['itag']}')

replace (') with (")
you know we can't use (' ') in (' ')

**Comment by jhj0517** [comment]
@JuanBindez Can you release a new version for this? 🥺 This happens in 6.15.0

**Comment by jonaskahn** [comment]
Fallback to 6.13.1 version should worked. Be patient util it fix

**Comment by JuanBindez** [comment]
Hello, it has already been fixed but I haven't released it yet, I will release it today.

**Comment by jonaskahn** [comment]
I tested, and it worked. Thanks, bro
