### ISSUE TITLE
KeyError for Search()

### ISSUE THREAD

**Issue by lunqwe** [JuanBindez/pytubefix#214]
Hello! When I use Search() an error occurs when receiving some data:

f'{items['reelItemRenderer']['videoId']}",
KeyError: 'reelItemRenderer'

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

vids = Search(query)
videos = vids.videos
for video in video_url:
      print(video.watch_url)

```

__________
**Expected behavior**
It should return url of a video 

__________

__________
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.10.0
 - Pytubefix Version 6.15.1

__________
**Additional context**
File pytubefix.contrib,search.py line 310

Its easy to fix just replacing f"{items['reelItemRenderer']['videoId']}",
 to f"{items.get('reelItemRenderer', {}).get('videoId', 'default_value')}"

**Comment by felipeucelli** [comment]
The fix is ​​now available in version 6.15.4.
