### ISSUE TITLE
[ENHANCEMENT] Channel profile image

### ISSUE THREAD

**Issue by sukhoi47** [JuanBindez/pytubefix#22]
@JuanBindez 

Do you have plans to implement the method to retrieve the Youtube channel "profile image" as recently implemented in [this patch for pytube](https://github.com/pytube/pytube/issues/1832#issuecomment-1837273279)?

**Comment by sukhoi47** [comment]
@JuanBindez I noticed you implemented the method to retrieve channel image.
Thank you! You are doing a very good job!

**Comment by JuanBindez** [comment]
> @JuanBindez I noticed you implemented the method to retrieve channel image. Thank you! You are doing a very good job!

Hello sukhoi47, I'm glad you're enjoying this project, it's not me doing a good job but the people who are contributing to keeping it updated and with new features.
