### ISSUE TITLE
python return: urllib.error.URLError: <urlopen error [WinError 10060]

### ISSUE THREAD

**Issue by DanielCHYH** [JuanBindez/pytubefix#221]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
python return: urllib.error.URLError: <urlopen error [WinError 10060]

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

# put your code here
pytubefix https://www.youtube.com/watch?v=BB7QgKU7cak

```

__________
**Expected behavior**

__________
**Screenshots**

python return: urllib.error.URLError: <urlopen error [WinError 10060] 
__________
**Desktop (please complete the following information):**
 - OS: [win10, pycharm]
 - Python Version [Python 3.11.7]
 - Pytubefix Version [6.15.4]

__________
**Additional context**

**Comment by jhanley-com** [comment]
NOT A BUG

The error code 10060 means it cannot connect to the remote peer.

I have verified that your URL works with PyTubeFix version 6.16.3 and Python 3.12.2.

The problem is with your application, proxy, network, etc and not with PyTubeFix.
