### ISSUE TITLE
Error to retrieve list of shorts: AttributeError: 'str' object has no attribute 'video_id'

### ISSUE THREAD

**Issue by NannoSilver** [JuanBindez/pytubefix#222]
New error that started a few hours ago.
Seems it affect only SHORTS.

I am running pytubefix 6.15.4 on Python 3.9.
The error was confirmed on Windows 11 and Ubuntu.

Code to test the error:
```
from pytubefix import Channel


youtube_channel_id = 'UC3g31jXrLf6AtIcjWDujeFw'
channel_url = f'https://youtube.com/channel/{youtube_channel_id}'
c = Channel(channel_url)
for short in c.shorts:
    episode_id = short.video_id
    print(episode_id)
```

Expected output:
`list of short videos`

Actual output:
```
Traceback (most recent call last):
  File "c:\Python projects\test21.py", line 8, in <module>
    episode_id = short.video_id
AttributeError: 'str' object has no attribute 'video_id'

Process finished with exit code 1
```

Seems something changed at Youtube.

**Comment by felipeucelli** [comment]
YouTube updated the json tree, test this PR #223  and tell us the result.

**Comment by NannoSilver** [comment]
> YouTube updated the json tree, test this PR #223 and tell us the result.

I just tested pytubefix 6.16.1 that includes PR #223 and the issue is fixed.
Thank you @felipeucelli and @JuanBindez for this excellent job.
