### ISSUE TITLE
Doubt: Can i get how many likes one video have?

### ISSUE THREAD

**Issue by 4d4m0r** [JuanBindez/pytubefix#224]
Can i get how many likes one video have?

**Comment by felipeucelli** [comment]
Great question, likes are obtained from the API's `next` endpoint. We will add this feature soon.

**Comment by 4d4m0r** [comment]
For data analysis, I also find numbers such as the number of comments and shares interesting. Somehow I managed to visualize the number of likes through watch_html, but it's not worth the effort.
