### ISSUE TITLE
new feature for blocked accounts

### ISSUE THREAD

**Issue by BilagoNet** [JuanBindez/pytubefix#225]
https://www.youtube.com/youtubei/v1/player?prettyPrint=false

this api works for any blocked ips/accounts

this i got by embed, see screenshot:

![cloud-photo-size-2-5415580446449851362-y](https://github.com/user-attachments/assets/105a90f9-cb9b-41f2-adb7-195d18ae417b)

**Comment by felipeucelli** [comment]
Great observation, but pytubefix already uses this endpoint.

The official WEB_EMBED client sends the PoToken in the payload, which allows access to accounts detected as bots. See more in #209.
