### ISSUE TITLE
This request was detected as a bot. Use `use_po_token=True` to view

### ISSUE THREAD

**Issue by abdwap** [JuanBindez/pytubefix#226]
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://www.youtube.com/embed/h7iDDiTBRis"

yt = YouTube(url, use_po_token=True)
           
ys = yt.streams.get_highest_resolution()
ys.download()
 
 
  File "/usr/local/lib/python3.8/site-packages/pytubefix/__main__.py", line 344, in check_availability
    raise exceptions.BotDetection(video_id=self.video_id)
pytubefix.exceptions.BotDetection: h7iDDiTBRis This request was detected as a bot. Use `use_po_token=True` to view

**Comment by AliGhadamyari** [comment]
I have the same issue!
is there any fix for it?!

**Comment by felipeucelli** [comment]
This error indicates that YouTube blocked your request, it occurs more frequently in cloud environments.

Delete the token cache and try using another PoToken and let us know the result. see instructions here #209.

**Comment by NannoSilver** [comment]
> This error indicates that YouTube blocked your request, it occurs more frequently in cloud environments.
> 
> Delete the token cache and try using another PoToken and let us know the result. see instructions here #209.

@felipeucelli

There are many people coming and opening this exactly same issue every few days.

My suggestion is to expand the output of this exception to the user.
In addition to `This request was detected as a bot. Use use_po_token=True to view` can be also added something like `See more details at https://github.com/JuanBindez/pytubefix/pull/209`

**Comment by felipeucelli** [comment]
@NannoSilver Great idea, I'll add this in the next PR.

**Comment by Kief5555** [comment]
> This error indicates that YouTube blocked your request, it occurs more frequently in cloud environments.
> 
> Delete the token cache and try using another PoToken and let us know the result. see instructions here #209.

Can you please let me know where to find the token cache so I can clear it?

**Comment by abdwap** [comment]
The token cache has been deleted 
But the problem persists

**Comment by abdwap** [comment]
It works when using a proxy 
But it does not work on the server ip 
I don't know why yet



from pytubefix import YouTube
from pytubefix.cli import on_progress
url = "https://www.youtube.com/watch?v=rLb8gn_4uLI"
proxies = {
    "https": 344444:444"
}
# Define the directory to save the video
save_dir = "/home/m/public_html/v"
yt = YouTube(
    url,
    proxies=proxies,use_po_token=True, allow_oauth_cache=True, token_file="/home/m/public_html/1.json",
    on_progress_callback=on_progress
)
ys = yt.streams.get_highest_resolution()
ys.download(output_path=save_dir)

**Comment by cleong110** [comment]
FYI, to get a po_token you can do like thus: https://colab.research.google.com/drive/190BC9tEc0wTtCsfSbWHY-lT6amjSwFyG#scrollTo=CHFMbX0n_KpB

Then I believe when you _use_ a YouTube object (not when you first create it!) then it will prompt you.

@felipeucelli how would it be possible to set the po_token programmatically instead of prompting the user? I had to create a YouTube object, then download a video (Rick Astley's Never Gonna Give You Up), and then subsequent connections/downloads then did not prompt me. But is there a way to pass in the info when creating it, or perhaps trigger the prompt manually without doing a download?

**Comment by cleong110** [comment]
What I can confirm is that after generating a po_token with that colab notebook above, and getting pytubefix to cache it, I was then able to successfully download additional videos

**Comment by felipeucelli** [comment]
> FYI, to get a po_token you can do like thus: https://colab.research.google.com/drive/190BC9tEc0wTtCsfSbWHY-lT6amjSwFyG#scrollTo=CHFMbX0n_KpB

Hello, would you mind sharing your colab notebook publicly, this link needs access authorization.

> Then I believe when you _use_ a YouTube object (not when you first create it!) then it will prompt you.
> 
> @felipeucelli how would it be possible to set the po_token programmatically instead of prompting the user? I had to create a YouTube object, then download a video (Rick Astley's Never Gonna Give You Up), and then subsequent connections/downloads then did not prompt me. But is there a way to pass in the info when creating it, or perhaps trigger the prompt manually without doing a download?


I'm working on improving user notices about PoToken.

PoToken generation is complex. [This project](https://github.com/LuanRT/BgUtils) seems to have managed to interact directly with the botguard API, I'm trying to implement it in python.

**Comment by cleong110** [comment]
@felipeucelli Ah, that's embarassing. Shared. tldr I just clone the token generator repo and run the example script with `node`

**Comment by cleong110** [comment]
Here's the whole thing, essentially:
```
npm install youtube-po-token-generator
git clone https://github.com/YunzheZJU/youtube-po-token-generator.git
node /content/youtube-po-token-generator/examples/one-shot.js
```

**Comment by cleong110** [comment]
Then I simply copy-pasted the resulting strings into my download script here: https://github.com/cleong110/explore-youtube-asl/blob/main/download_vids.py#L343-L351

**Comment by felipeucelli** [comment]
I haven't found a way to generate the PoToken programmatically in Python yet, but you can try to create a custom function that interacts with your colab code and passes it to Pytubefix using for example: 
```python
YouTube('URL', use_po_token=True, po_token_verifier=YOUR-FUNCTION)
```

**Comment by yannickErp** [comment]
> I haven't found a way to generate the PoToken programmatically in Python yet, but you can try to create a custom function that interacts with your colab code and passes it to Pytubefix using for example:
> 
> ```python
> YouTube('URL', use_po_token=True, po_token_verifier=YOUR-FUNCTION)
> ```

Has anyone successfully deployed this on AWS Lambda or EC2 etc.?

**Comment by cleong110** [comment]
Here's an issue I just noticed, it seems that the token generator always gets the same token: https://github.com/YunzheZJU/youtube-po-token-generator/issues/2

**Comment by cleong110** [comment]
Also the instructions to get it manually, I was not able to follow, possibly because I'm not familiar with the console (I used Edge). I found some things that might be right, but looking through them, I was not able to find a potoken. Example: 
![image](https://github.com/user-attachments/assets/85e67189-f71b-4a87-aef5-1999a32da890)
![image](https://github.com/user-attachments/assets/e67172ca-dbf5-402b-bf74-a52c22578fdf) here it actually uses serviceIntegrityDimensions.poToken but I don't know how to get the value out

**Comment by felipeucelli** [comment]
Open an embedded YouTube url, press play and try this:
![IMG-20240918-WA0004](https://github.com/user-attachments/assets/f106f636-8a03-4a7e-abe5-0a10aef88634)

I used chrome, but the process is the same on edge.

**Comment by cleong110** [comment]
Ah, that works. Also the javascript solution is working again, false alarm from me.

**Comment by PistacheDev** [comment]
For me, turn off my VPN fixed the problem.

**Comment by amrrs** [comment]
I got the tokens manually but I don't know to add it a web app that I'm going to host on aws

**Comment by gayuna** [comment]
Is there any way to input Visitor Data and PO Token as a parameter
instead of input function?
I'd like to build a workflow using [youtube-po-token-generator.git](https://github.com/YunzheZJU/youtube-po-token-generator.git) before run python script and pass it as a parameter to python script and just don't have idea how to.

**Comment by totohoon02** [comment]
@gayuna 
I'm not sure this might helpful, I used selenium to get po-token and tried to cache it with token_file paramater
[https://github.com/totohoon02/yt_po_token_generator_python](https://github.com/totohoon02/yt_po_token_generator_python )

**Comment by HiveYuan** [comment]
> @gayuna I'm not sure this might helpful, I used selenium to get po-token and tried to cache it with 'token_file' paramater In my case I still get use_po_token error though.. https://github.com/totohoon02/yt_po_token_generator_python

Same for me. I used the js script to generate the po_token and visitorData, but it still says "detected as a bot". Anyone know would there be any other reasons?

**Comment by ajay-sreeram** [comment]
> @gayuna I'm not sure this might helpful, I used selenium to get po-token and tried to cache it with 'token_file' paramater In my case I still get use_po_token error though.. https://github.com/totohoon02/yt_po_token_generator_python

yes same for me, still getting the error

**Comment by HiveYuan** [comment]
您好，我已收到您的邮件并会尽快处理，祝您工作顺利，生活愉快！——刘源

**Comment by aajinkya1203** [comment]
> > This error indicates that YouTube blocked your request, it occurs more frequently in cloud environments.
> > Delete the token cache and try using another PoToken and let us know the result. see instructions here #209.
> 
> Can you please let me know where to find the token cache so I can clear it?

/site-packages/pytubefix/__cache__/tokens.json

**Comment by HiveYuan** [comment]
您好，我已收到您的邮件并会尽快处理，祝您工作顺利，生活愉快！——刘源

**Comment by JuanBindez** [comment]
> > > This error indicates that YouTube blocked your request, it occurs more frequently in cloud environments.
> > > Delete the token cache and try using another PoToken and let us know the result. see instructions here #209.
> > 
> > 
> > Can you please let me know where to find the token cache so I can clear it?
> 
> /site-packages/pytubefix/**cache**/tokens.json

in version 8.5.1 you can clear the cache by calling the reset_cache() function see:   https://github.com/JuanBindez/pytubefix/pull/333

**Comment by Donadev56** [comment]
> from pytubefix import YouTube from pytubefix.cli import on_progress
> 
> url = "https://www.youtube.com/embed/h7iDDiTBRis"
> 
> yt = YouTube(url, use_po_token=True)
> 
> ys = yt.streams.get_highest_resolution() ys.download()
> 
> File "/usr/local/lib/python3.8/site-packages/pytubefix/**main**.py", line 344, in check_availability raise exceptions.BotDetection(video_id=self.video_id) pytubefix.exceptions.BotDetection: h7iDDiTBRis This request was detected as a bot. Use `use_po_token=True` to view

hello , i have solve this problem and i want to share with you how i did that , 


firstly go to smartproxy.com purchase a residential proxy and get your proxies links and access 

once it is done go to your setup and add a proxy params 

exemple  : my_proxies = {
    http://your-http-proxy,
    https://your-https-proxy 

}

yt = Youtube(yrl , proxies=my_proxies)
![Uploading Capture d’écran 2024-12-01 à 02.20.22.png…]()



it will directly solve the issue

**Comment by Pksb755** [comment]
Is there not any solution other than proxy server or smartproxy.com purchase a residential proxy.
I does not want to use the proxy setup.

**Comment by HiveYuan** [comment]
您好，我已收到您的邮件并会尽快处理，祝您工作顺利，生活愉快！——刘源

**Comment by Donadev56** [comment]
> Is there not any solution other than proxy server or smartproxy.com purchase a residential proxy.
> I does not want to use the proxy setup.

There are several solutions. I chose smart proxy because it is the fastest and most functional. In any case, that's what I noticed on my side

**Comment by Donadev56** [comment]
> Is there not any solution other than proxy server or smartproxy.com purchase a residential proxy.
> I does not want to use the proxy setup.

There are several solutions. I chose smart proxy because it is the fastest and most functional. In any case, that's what I noticed on my side

**Comment by Joe-Tabet** [comment]
@cleong110 **you are the King man**  thank you for the source "https://colab.research.google.com/drive/190BC9tEc0wTtCsfSbWHY-lT6amjSwFyG#scrollTo=CHFMbX0n_KpB"

run this in cmd After installing node js https://nodejs.org/en
"npm install youtube-po-token-generator"
then use yt = Youtube(url,'WEB') in your code and it should work

**Comment by HiveYuan** [comment]
您好，我已收到您的邮件并会尽快处理，祝您工作顺利，生活愉快！——刘源

**Comment by hamido888** [comment]
Go to the innertube.py file and change the


`def __init__(
self,
client='ANDROID',
use_oauth=False,
allow_cache=True,
token_file=None,
oauth_verifier=None,
use_po_token=False,
po_token_verifier=None`

to

`def __init__(
self,
client='WEB',
use_oauth=False,
allow_cache=True,
token_file=None,
oauth_verifier=None,
use_po_token=False,
po_token_verifier=None`

**Comment by IROSHENZER** [comment]
> [@cleong110](https://github.com/cleong110) **you are the King man** thank you for the source "https://colab.research.google.com/drive/190BC9tEc0wTtCsfSbWHY-lT6amjSwFyG#scrollTo=CHFMbX0n_KpB"
> 
> run this in cmd After installing node js https://nodejs.org/en "npm install youtube-po-token-generator" then use yt = Youtube(url,'WEB') in your code and it should work

I've test this several times but it doesn't work. Is there any other way?

**Comment by HiveYuan** [comment]
您好，我已收到您的邮件并会尽快处理，祝您工作顺利，生活愉快！——刘源
