### ISSUE TITLE
  "error": "'inlinePlayerData'"

### ISSUE THREAD

**Issue by ExyXyz** [JuanBindez/pytubefix#227]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
idk why when i try to search using keyword "no vitality" it shows that    "error": "'inlinePlayerData'"
__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

# put your code here
@app.route('/api/yts', methods=['GET'])
def search_videos():
    query = request.args.get('q')

    if not query:
        return jsonify({"error": "No search query provided | Gaada judul yang dikasih"}), 400

    try:
        results = Search(query)

        if not results.videos:
            return jsonify({"error": "No videos found | Tidak ada video yang ditemukan"}), 404

        videos = []
        for video in results.videos:
            yt = YouTube(video.watch_url, use_oauth=True, allow_oauth_cache=True, on_progress_callback=on_progress)

            videos.append({
                "1_title": yt.title,
                "2_thumbnail": yt.thumbnail_url,
                "3_url": yt.watch_url,
                "4_author": yt.author,
                "5_duration": yt.length
            })

        return jsonify({"videos": videos})

    except Exception as e:
        return jsonify({"error": str(e)}), 500

```

__________
**Expected behavior**
I expected it shows the result but it doesnt

__________
**Screenshots**
![image](https://github.com/user-attachments/assets/1f0731b2-da18-494a-b9e3-fd92041fc340)

__________
**Desktop (please complete the following information):**
 - OS: [Windows 11 | Linux Ubuntu VPS digital ocean (idk the version)]
 - Python Version [Windows : 3.12.4 | Vps : 3.8.10 ]
 - Pytubefix Version [6.16.1]

__________
**Additional context**
I tested both in windows and vps and its the same idk why
it just the youtube search the download still no problem
i might be dumb so yeah help me pls

**Comment by felipeucelli** [comment]
I tested your code and it works for me, maybe YouTube is implementing A/B tests.

Would you mind taking a test?

On line **312** of the **search.py** ​​file change this:

```python
video_id = items['shortsLockupViewModel']['inlinePlayerData']['onVisible'][
                                'innertubeCommand']['watchEndpoint']['videoId']

```

for this

```python
 video_id = items['shortsLockupViewModel']['onTap']['innertubeCommand']['reelWatchEndpoint']['videoId']
```

**Comment by ExyXyz** [comment]
> I tested your code and it works for me, maybe YouTube is implementing A/B tests.
> 
> Would you mind taking a test?
> 
> On line **312** of the **search.py** ​​file change this:
> 
> ```python
> video_id = items['shortsLockupViewModel']['inlinePlayerData']['onVisible'][
>                                 'innertubeCommand']['watchEndpoint']['videoId']
> ```
> 
> for this
> 
> ```python
>  video_id = items['shortsLockupViewModel']['onTap']['innertubeCommand']['reelWatchEndpoint']['videoId']
> ```

i tried this and it's working thank you so much
