### ISSUE TITLE
is there any Thread lock?

### ISSUE THREAD

**Issue by sleepingcat4** [JuanBindez/pytubefix#229]
I had been downloading videos in parallel before using pytube and pytube fix by loading multiple urls and multiple threads (1 thread = 1url) but in the most recent version no matter how hardcore I mentioned for it download all the loaded videos on each thread at same time it downloads sequentially. Which sucks. 

is there any thread lock or internal lock in place that was written in the most recent versions? @JuanBindez

**Comment by felipeucelli** [comment]
This PR #218 added a download interruption parameter. But I can't test if it's what's causing your problem.

**Comment by sleepingcat4** [comment]
@felipeucelli what was the last version before this param was included? I can try out that version. I have been experiencing this for 2 weeks now.

**Comment by felipeucelli** [comment]
Test pytubefix==6.15.4

**Comment by fedetony** [comment]
Just a suggestion, you could try to use [asyncio](https://docs.python.org/3/library/asyncio.html) python package instead of multithreading. [Here](https://realpython.com/async-io-python/) a detail description. :)
