### ISSUE TITLE
I have a problem with using SOCKS5 proxies in pytubefix.

### ISSUE THREAD

**Issue by florestdev** [JuanBindez/pytubefix#233]
I have got this error: Произошла ошибка: <urlopen error [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение>
This error is coming to me. when I'm using my SOCKS5 proxie. Please help me to solve this error.

**Comment by NannoSilver** [comment]
Show here your code that is leading to such error

**Comment by florestdev** [comment]
> Share here your code that is leading to such error

``````
def download():
    yt = YouTube('url', proxies={"socks5":"socks5 proxy", "socks5":""socks5 proxy"})        
 yt.streams.get_audio_only().download(True
`````

**Comment by JuanBindez** [comment]
> > Share here your code that is leading to such error
> 
> ```
> def download():
>     yt = YouTube('url', proxies={"socks5":"socks5 proxy", "socks5":""socks5 proxy"})        
>  yt.streams.get_audio_only().download(True
> `````
> ```

try:

    proxies={"http": "socks5://proxy_address", "https": "socks5://proxy_address"}

**Comment by yannickErp** [comment]
Where do you guys get your proxies from? Are they not super expensive and/or slow?

**Comment by florestdev** [comment]
> Where do you guys get your proxies from? Are they not super expensive and/or slow?

I bought this proxy in proxy6.net. Type: Soscks5
In another applications works cool.

**Comment by JuanBindez** [comment]
An observation that may be important, some applications may bypass the SOCKS5 proxy or make direct connections that expose their real IP, to resolve this you must force your scripts to pass through the proxy.
