### ISSUE TITLE
Unknown video status

### ISSUE THREAD

**Issue by Onyoursix** [JuanBindez/pytubefix#235]
__________
**Describe the bug**

I'm getting the following error:

```
09-17-2024 Regular Commission Meeting
Unknown Video Error
Video ID: BmboDab-2aI
Status: OK
Reason: This live event has ended.
Developer Message: Unknown video status
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide the above log output.
Traceback (most recent call last):
  File "/home/six/speech_to_text/pytube_test.py", line 8, in <module>
    ys = yt.streams.get_highest_resolution()
  File "/home/six/speech_to_text/speech1/lib/python3.10/site-packages/pytubefix/__main__.py", line 602, in streams
    self.check_availability()
  File "/home/six/speech_to_text/speech1/lib/python3.10/site-packages/pytubefix/__main__.py", line 374, in check_availability
    raise exceptions.UnknownVideoError(video_id=self.video_id, status=status, reason=reason, developer_message=f'Unknown video status')
pytubefix.exceptions.UnknownVideoError: BmboDab-2aI has an unknown error, check logs for more info
```

Seems there is an issue with the status that comes back as "OK" which isn't accounted for in the "check_availability" function in __main__.py I tried editing line 369 to `elif status == None or status == "OK"` but then I get a "AttributeError: 'NoneType' object has no attribute 'download'" 

Any idea?

Most other videos work, I suspect this may be an issue with videos that were live streamed. I'm not 100% on that though.

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = 'https://www.youtube.com/watch?v=BmboDab-2aI'
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()


```

__________
**Expected behavior**
The video to download.

__________
**Desktop (please complete the following information):**
 - OS: Ubuntu/Linux
 - Python Version 3.10.12
 - Pytubefix Version 6.16.12

**Comment by NannoSilver** [comment]
I tried your code and got the same error.

Usually the lives only become available to download after a few hours, but in some rare cases may take a few days.
Try again tomorrow to check if is the case.

**Comment by Onyoursix** [comment]
> I tried your code and got the same error.
> 
> Usually the lives only become available to download after a few hours, but in some rare cases may take a few days. Try again tomorrow to check if is the case.

I wasn't aware of that, I'll check tomorrow and report back. Thanks!

**Comment by jhanley-com** [comment]
NOT A BUG.

This should be closed. It is not a PyTubeFix error.

The video was not available. It is now available. That issue is unrelated to PyTubeFix.
