### ISSUE TITLE
error": "91mh1QTkwJnX0E is unavailable"

### ISSUE THREAD

**Issue by ExyXyz** [JuanBindez/pytubefix#239]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
So i tried to download something with my localhost API it just showing this message 
error": "\u001B[91mh1QTkwJnX0E is unavailable\u001B[0m

__________
**code that was used that resulted in the bug**

```python
from flask import Flask, request, send_file, jsonify, send_from_directory, url_for, redirect
import os
import random
import threading
import time
import re
from flask_cors import CORS
from pytubefix import YouTube
from pytubefix.cli import on_progress

app = Flask(__name__)
CORS(app)

@app.route('/api/ytmp3', methods=['GET'])
def download_audio():
    video_url = request.args.get('url')

    if not video_url:
        return jsonify({"error": "No video URL provided | Link nya manah?"}), 400

    try:
        yt = YouTube(video_url, use_oauth=True, allow_oauth_cache=True, on_progress_callback=on_progress)
        
        ys = yt.streams.get_audio_only()

        random_number = random.randint(1, 10000)
        sanitized_title = re.sub(r'[^a-zA-Z0-9_-]', '', yt.title).replace(' ', '_')
        audio_mp3_filename = os.path.join('download', f'audio_{sanitized_title}_{random_number}')

        ys.download(filename=audio_mp3_filename, mp3=True)

        download_link = f'https://localhost:80/download/{os.path.basename(audio_mp3_filename)}.mp3'

        return jsonify({
            "1_title": yt.title,
            "2_thumbnail": yt.thumbnail_url,
            "3_artist": yt.author,
            "4_views": yt.views,
            "5_duration": yt.length,
            "6_url": yt.watch_url,
            "7_download_link": download_link
        })
    
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    
@app.route('/download/<filename>', methods=['GET'])
def download_file(filename):
    file_path = os.path.join('download', filename)
    if not os.path.exists(file_path):
        return jsonify({"message": "More than 100 sec has passed | Sudah lewat dari 100 detik"}), 404
    return send_file(file_path, as_attachment=True, mimetype='video/mp4')

def delete_old_files():
    while True:
        time.sleep(5000)
        for filename in os.listdir('download'):
            file_path = os.path.join('download', filename)
            if (filename.startswith('ytdl_') or filename.startswith('audio_')) and (filename.endswith('.mp4') or filename.endswith('.mp3')):
                os.remove(file_path)
                print(f"Deleted {filename}")

deletion_thread = threading.Thread(target=delete_old_files, daemon=True)
deletion_thread.start()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80)

```

__________
**Expected behavior**
I expect that it will download as usual but its not

__________
**Screenshots**
![image](https://github.com/user-attachments/assets/1ddd7562-226e-4f3a-be74-a0ff373c4911)
![image](https://github.com/user-attachments/assets/1fbfb7e6-9d08-41c4-879b-aae75aa9d2bc)

__________
**Desktop (please complete the following information):**
 - OS: [Windows | Digital Ocean VPS Linux Ubuntu]
 - Python Version [3.12.4 | 3.8.10]
 - Pytubefix Version [6.16.3]

__________
**Additional context**
i might be dumb so yeah can someone help me

**Comment by jhanley-com** [comment]
Your YouTube ID has ANSI color codes embedded. The problem is with your code/app/VideoID and not with PyTubeFix.

The working URL is https://www.youtube.com/watch?v=grQ9m-fVKZQ

I have verified that that URL works with versions 6.15.4 and 6.16.3 and Python 3.12.2.

For proof, here is a list of the audio stream from that ID:

Audio Streams:
    1,369,902 audio/mp4  48kbps      mp4a.40.5   139 None audio
    3,633,852 audio/mp4  128kbps     mp4a.40.2   140 None audio
    1,457,790 audio/webm 50kbps           opus   249 None audio
    1,916,801 audio/webm 70kbps           opus   250 None audio
    3,745,844 audio/webm 160kbps          opus   251 None audio
