### ISSUE TITLE
New bug - Slice must be applied on a list in : a.slice(0, 0)

### ISSUE THREAD

**Issue by robochopbg** [JuanBindez/pytubefix#240]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**

This happens when selecting a youtube stream to play.
Not all the time but is starting to happen more often now.
So has something changed again on Google/Youtube side ??

File "C:\Python310\lib\site-packages\pytubefix\jsinterp.py", line 874, in assertion
    raise self.Exception(f'{member} {msg}', expr)
pytubefix.jsinterp.JSInterpreter.Exception: slice must be applied on a list in: a.slice(0,0)
__________
**code that was used that resulted in the bug**

from pytubefix import Search, YouTube, Stream

def get_youtube_stream(self, id: str, title: str):
      KThread(
          name=self.get_youtube_stream.__name__, 
          target=self.get_stream, args=(id, title)
      ).start()
        
def get_stream(self, id: str, title: str):
    try:
        stream: Stream = self.get_url(id)
    except Exception:
        print("error", "".join(traceback.format_exc().rstrip("\n")))
    else:
        if stream is not None:
            self.send_disp_event(
                Inst.VLCMgr, {EType.Network: [stream.url, title]}
            )
    
def get_url(self, video_id: str) -> str:
    video_url = f"https://www.youtube.com/watch?v={video_id}"
    yt = YouTube(video_url)
    return yt.streams.get_highest_resolution()

__________
**Expected behavior**

Well i never used to get this error before.
I would search for youtube videos into a table then i play a video and it starts to stream.
Now all of a sudden this new error appears about slice should be applied on a list.
Code has not been changed on my side for this to happen.

__________
**Screenshots**

![error](https://github.com/user-attachments/assets/904a3dc7-8e98-4317-b4c3-ede2c123483a)

__________
**Desktop (please complete the following information):**

Windows 10 Pro - 22H2
Python 3.10.7 final
Pytubefix - 5.7.0

__________
**Additional context**

**Comment by felipeucelli** [comment]
This issue has already been fixed, please update to the latest version of pytubefix.

**Comment by robochopbg** [comment]
Thank you
