### ISSUE TITLE
Youtube().title doesn't return slash symbols

### ISSUE THREAD

**Issue by DialVeleon** [JuanBindez/pytubefix#243]
__________
**Bug description**
YouTube().title doesn't returns "/" symbols in title but YouTube().vid_info["videoDetails"]["title"] returns it

__________
**Code that was used that resulted in the bug**

```python
from pytubefix import YouTube

yt = YouTube("https://youtu.be/J25rZkdlZkE")
print(yt.title == yt.vid_info["videoDetails"]["title"])
print(yt.title)
print(yt.vid_info["videoDetails"]["title"])
```

__________
**Desktop:**
 - OS: android aarch64 termux 0.118.1 (linux emulator for android)
 - Python Version 3.11.9
 - Pytubefix Version 6.16.3

**Comment by JuanBindez** [comment]
see:   https://pytubefix.readthedocs.io/en/latest/user/problematic_characters.html

**Comment by DialVeleon** [comment]
Thank you, it works
