### ISSUE TITLE
pytubefix don't work as expected

### ISSUE THREAD

**Issue by ATPDS** [JuanBindez/pytubefix#245]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
when launch the pytubefix don't get the video but it still get the title

Titan TR Digital 30 PETD3091000H CreativeX sm
Traceback (most recent call last):
  File "/home/tul/Desktop/project/ILI9341/yt.py", line 10, in <module>
    ys = yt.streams.get_highest_resolution()
  File "/home/tul/.local/lib/python3.11/site-packages/pytubefix/__main__.py", line 629, in streams
    self.check_availability()
  File "/home/tul/.local/lib/python3.11/site-packages/pytubefix/__main__.py", line 335, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytubefix.exceptions.VideoUnavailable: [91mDFI51983fvw is unavailable[0m

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress
url = 'https://www.youtube.com/watch?v=DFI51983fvw'
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
ys = yt.streams.get_highest_resolution()
ys.download()

```

__________
**Expected behavior**
Download the video

__________
**Desktop (please complete the following information):**
 - OS: [Debian GNU/Linux 12 (bookworm)]
 - Python Version [3.11.2]
 - Pytubefix Version [6.17.0]

__________

**Comment by JuanBindez** [comment]
Try pytubefix==7.0rc1

Em qua., 25 de set. de 2024 00:54, ATPDS ***@***.***>
escreveu:

**Comment by ATPDS** [comment]
Thank you. that work for me!
