### ISSUE TITLE
Playlist length bug

### ISSUE THREAD

**Issue by shandralor** [JuanBindez/pytubefix#247]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
When downloading a playlist that is longer than 100 items I receive an Error: HTTP Error 400: Bad Request

__________
**code that was used that resulted in the bug**

```python
import os
from pytubefix import YouTube, Playlist
from pytubefix.cli import on_progress
import time
import random
 
 
def download_video(video_url, output_directory):
    retry = 0
    max_retries = 3

    while retry < max_retries:
        try:
            yt = YouTube(video_url, client='WEB_CREATOR', on_progress_callback=on_progress)
            ys = yt.streams.get_audio_only()
            print(f'Downloading video: {yt.title}')
            ys.download(output_path=output_directory, mp3=True)
            return

        except Exception as e:
            print(f'An error occurred: {e}')

            # Wait for a random interval between 1-5 seconds before retrying
            time.sleep(random.uniform(1, 5))

            retry += 1

    
 
def main():
    url = input('Enter the URL of the YouTube video or playlist: ')
    playlist_passed = 'playlist' in url

    output_dir = os.path.join(os.getcwd(), 'Downloads') 

    if not os.path.exists(output_dir):  
        os.makedirs(output_dir)
    try:
        if playlist_passed:
            
            print('Downloading playlist')
            pl = Playlist(url, client='WEB_CREATOR')
            
            for video_url in pl.video_urls:
               print(video_url)
                
        else:
            download_video(url, output_dir)
    except Exception as e:
        print(f'An error occurred: {e}')
    
    print()
    print('Download complete.')
    
if __name__ == '__main__':
    main()


```

__________
**Expected behavior**
I would like to be able to use playlists longer than 100 videos

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: Windows 11  23H2
 - Python Version [3.12.3]
 - Pytubefix Version [6.17.0]

__________
**Additional context**

**Comment by jhanley-com** [comment]
What is the Playlist URL?

**Comment by shandralor** [comment]
https://www.youtube.com/playlist?list=PLAB6jimK6CqdXxbqqSyNHTBUWvEiE8qvV

I tested with removing a song from the playlist and it did download one additional song before throwing the error, again stopping at 100 songs

**Comment by felipeucelli** [comment]
The fix is available in this PR #249

**Comment by JuanBindez** [comment]
try: pytubefix==7.1rc1

**Comment by shandralor** [comment]
You fixed it with the version above! Thx for this!
