### ISSUE TITLE
Error: "{video_id} is streaming live and cannot be loaded" when video stream was finished

### ISSUE THREAD

**Issue by KIT64** [JuanBindez/pytubefix#248]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
pytubefix.exceptions.LiveStreamError: q85fNQA071k is streaming live and cannot be loaded

I get this error for every streamed video that was finished and is no longer streaming live.
__________
**code that was used that resulted in the bug**

```from pytubefix import YouTube
from pytubefix.cli import on_progress

def main():
    url = "https://www.youtube.com/watch?v=q85fNQA071k"
    video = YouTube(url, on_progress_callback=on_progress)
    highest_resolution_stream = video.streams.get_highest_resolution()
    highest_resolution_stream.download()

if __name__ == "__main__":
    main()
```

__________
**Expected behavior**
Live video that has their stream finished already should be able to download.

__________
**Screenshots**
![image](https://github.com/user-attachments/assets/14a76f6b-356f-4f24-bf9f-9bf950f78042)

__________
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 22H2
 - Python Version: 3.11.4
 - Pytubefix Version 7.0.0

__________
**Additional context**

**Comment by neosubhamoy** [comment]
I am experiencing the same issue with every **Premiered Video** on YouTube. I noticed it earlier when I tried  `ANDROID_VR` client for the first time to fix: #242 on Pytubefix 6.17.6. So, maybe it's caused by `ANDROID_VR` client (which is now the default from Pytubefix 7.0.0 replacing `ANDROID_TESTSUITE`). Still didn't got any workaround....!!! (Currently I'm sticked to `ANDROID_VR` cause: other clients are even performing worse ;-)
____
**My System:**

- OS: Windows 11 23H2
- Python: 3.12.5
- Pytubefix: 7.0.0

**Comment by JuanBindez** [comment]
it takes a while

**Comment by jhanley-com** [comment]
Please do not post screenshots of code and error messages. That makes copy and paste difficult and search engines do not index text in images.

**Comment by NannoSilver** [comment]
@JuanBindez @felipeucelli 

Every week somebody comes with this same "issue".

My suggestion is to improve the error message shown to the user to something like this:

_g85fNQA071k is streaming live and cannot be loaded. **Lives usually are available to download only after a few hours of its ending, and in some rare cases only after a few days**._

**Comment by JuanBindez** [comment]
I thought it was great

**Comment by JuanBindez** [comment]
I'm going to do the following, I'm going to create a branch to be improved and review all the exceptions, so we can work on them

**Comment by KIT64** [comment]
> @JuanBindez @felipeucelli
> 
> Every week somebody comes with this same "issue".
> 
> My suggestion is to improve the error message shown to the user to something like this:
> 
> _g85fNQA071k is streaming live and cannot be loaded. **Lives usually are available to download only after a few hours of its ending, and in some rare cases only after a few days**._

The thing is that videos that I tried to download finished their stream 2-4 months ago

**Comment by felipeucelli** [comment]
ANDROID_VR is returning 'liveStreamability' in some videos causing false errors.

We will have to try to improve video verification, or change the client to baseddos on WEB or IOS.

**Comment by neosubhamoy** [comment]
> ANDROID_VR is returning 'liveStreamability' in some videos causing false errors.
> 
> We will have to try to improve video verification, or change the client to baseddos on WEB or IOS.

@JuanBindez @NannoSilver 

I think this is the real issue currently happening as @felipeucelli said and it's not the Error Message (Videos I tried were even premiered / live streamed more than 6 months ago). It's just a false error caused by `ANDROID_VR` client which is not there previously with `ANDROID_TESTSUITE` (When it's requests are not blocked by YouTube). So, we should fix this false error thing first (there are lots of Premiered Videos on YouTube that are currently inaccessible). This issue is highly affecting the overall usability of the library....!!

**Comment by NannoSilver** [comment]
> > ANDROID_VR is returning 'liveStreamability' in some videos causing false errors.
> > We will have to try to improve video verification, or change the client to baseddos on WEB or IOS.
> 
> @JuanBindez @NannoSilver
> 
> I think this is the real issue currently happening as @felipeucelli said and it's not the Error Message (Videos I tried were even premiered / live streamed more than 6 months ago). It's just a false error caused by `ANDROID_VR` client which is not there previously with `ANDROID_TESTSUITE` (When it's requests are not blocked by YouTube). So, we should fix this false error thing first (there are lots of Premiered Videos on YouTube that are currently inaccessible). This issue is highly affecting the overall usability of the library....!!

I started to have this issue too.
Live streaming, even streamed months ago, are throwing the error:
**_6dgt87S0c1k is streaming live and cannot be loaded_**

**Comment by jaferrando** [comment]
This is not the typical time to have the video available issue. The video I'm testing with ended streaming live almos 24h ago and can be downloaded from online services (I had to revert to them for this error)

**Comment by NannoSilver** [comment]
As mention by @felipeucelli , a temporary fix is to change the client to "**MWEB**", as in the example below.
MWEB is the non-poToken client on Pytubefix version 7.1rc1
Keep in mind that MWEB client requires a heavy processing, that may disrupt some servers.


```
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = "https://youtu.be/FruGLwA8JP8"

yt = YouTube(url, on_progress_callback=on_progress, client='MWEB')

print(yt.title)

ys = yt.streams.get_by_itag(140)
ys.download()
```

**Comment by felipeucelli** [comment]
Maybe I was able to fix this problem, would you mind testing this PR #253.

**Comment by NannoSilver** [comment]
> Maybe I was able to fix this problem, would you mind testing this PR #253.

It is working

**Comment by KIT64** [comment]
Yes, works now installing pytubefix==7.1rc2. Thanks!

**Comment by alekskorovin** [comment]
I could confirm it works. To update dependency use `pip install -Iv pytubefix==7.1rc2`
