### ISSUE TITLE
Private videos cannot be downloaded

### ISSUE THREAD

**Issue by TaiwanSUNA** [JuanBindez/pytubefix#250]
error:aHKmFuu23zo is unavailable

import ssl
ssl._create_default_https_context = ssl._create_stdlib_context

from pytubefix import YouTube
from pytubefix.cli import on_progress
import os
os.chdir('C:/Users/Downloads')
try:
	yt = YouTube('https://www.youtube.com/watch?v=aHKmFuu23zo', use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)

	yt.streams.filter().get_highest_resolution().download(filename='Harvestella_BGM.mp4')
except Exception as e:
print(f"error: {e}")

**Comment by asil004** [comment]
the same issue

**Comment by dkrystki** [comment]
Same here

**Comment by TaiwanSUNA** [comment]
I found the problem
I forgot to check if I updated to the latest version
It can be used normally after updating to the latest version.


pip install --upgrade pytubefix
