### ISSUE TITLE
There is just one option to download video with audio/its quality is bad (not confident whether it is bug or it is expected response)

### ISSUE THREAD

**Issue by markokovalua** [JuanBindez/pytubefix#257]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

There is just one option to download video with audio (not confident whether it is bug or it is expected response).
__________
**Describe the bug**

Hello, I have tried to download youtube video via `pytubefix` and got just one option to download video with audio. The resolution of the video is bad. Could you please help whether it is possible to download video with audio and with good resolution, thanks in advance. 
__________
**code that was used that resulted in the bug**

```python

from pytubefix import YouTube
from pytubefix.cli import on_progress

url = "https://www.youtube.com/watch?v=MBMz-eIU04M"

yt = YouTube(url, on_progress_callback=on_progress)
ys = yt.streams.get_highest_resolution()
ys.download()


# put your code here

```

__________
**Expected behavior**

video with audio but bad quality

https://drive.google.com/file/d/1k0b_q9fOiK2ESW-G3qWST3xuQrc0oFxY/view?usp=sharing

video without audio but good quality

https://drive.google.com/file/d/1zgjoai47uvdNX4QkqoNRBscGSuksmqFL/view?usp=sharing

would like to download a video with good quality and with audio 

__________
**Screenshots**

`-> ys.download()
(Pdb) ys
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">`

```
(Pdb) yt.streams

[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028" progressive="False" type="video">, <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001f" progressive="False" type="video">, <Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">]
```

`
(Pdb) yt.streams.filter(progressive=True)
[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">]
`

![Screenshot 2024-10-01 at 18 18 24](https://github.com/user-attachments/assets/cd8928ae-487e-4b44-be2a-72c9d7fd848a)

__________
**Desktop (please complete the following information):**
 - OS: Macos Montarey
 - Python Version Python 3.11.3
 - Pytubefix Version pytubefix==7.1.3

__________
**Additional context**

**Comment by jhanley-com** [comment]
Not a bug.

Your code is downloading the Progressive stream. For your URL that is 360p.

Suggestion. Learn about audio and video streams and how to work with them.
