### ISSUE TITLE
[Search] KeyError: 'onResponseReceivedCommands'

### ISSUE THREAD

**Issue by felipeucelli** [JuanBindez/pytubefix#261]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**

PR #255  made some changes that break the search when passing a client to the contractor.

If no client is passed, it works, but this can break several features of the Search class.
__________
**code that was used that resulted in the bug**

```python
from pytubefix import Search

s = Search('music', client='MWEB')
print(s.videos)
s.get_next_results()
print(s.videos)

```

__________
**Expected behavior**

get_next_results() performs pagination of the search results and fetches the next results.
__________
**Screenshots**

![Screenshot_20241003-084127~2](https://github.com/user-attachments/assets/20df16ab-94c1-452a-992e-7fb25ac82e7e)

__________
**Desktop (please complete the following information):**
 - OS: [Ubuntu server 24.04.1 LTS]
 - Python Version [3.10.12]
 - Pytubefix Version [7.2.2]

__________
**Additional context**

**Comment by JuanBindez** [comment]
I'll see here what it is

**Comment by felipeucelli** [comment]
I have some lines commented out, but I only sent the code needed for testing.

**Comment by felipeucelli** [comment]
I am developing a complete filter system, I will make the PR soon

**Comment by JuanBindez** [comment]
removing the client is working

```python
>>> from pytubefix import Search
>>> 
>>> s = Search('music')
>>> 
>>> s.get_next_results()
>>> 
>>> for video in s.videos:
...     print(f'Title: {video.title}')
...     print(f'URL: {video.watch_url}')
...     print(f'Likes: {video.likes}')
...     print(f'Duration: {video.length} sec')
...     print('-' * 40)
... 
Title: The Weeknd – Timeless with Playboi Carti (Official Music Video)
URL: https://youtube.com/watch?v=5EpyN_6dqyk
Likes: 279662
Duration: 256 sec
----------------------------------------
Title: Top hits 2024 playlist  ~ Trending music 2024 ~ Best songs 2024 updated weekly (Playlist Hits)
URL: https://youtube.com/watch?v=U0ZoqmyGJo8
Likes: 27675
Duration: 3796 sec
----------------------------------------
Title: Ibiza Summer Mix 2024 🍓 Best Of Tropical Deep House Music Chill Out Mix 2023 🍓 Chillout Lounge
URL: https://youtube.com/watch?v=KJ-hOud6mwo
Likes: None
Duration: 12670 sec
----------------------------------------
Title: Mega Hits 2024 🌱 The Best Of Vocal Deep House Music Mix 2024 🌱 Summer Music Mix 2024 #136
URL: https://youtube.com/watch?v=BCbr55A7ECc
Likes: None
Duration: 13711 sec
----------------------------------------
Title: Ibiza Summer Mix 2024 🍓 Best Of Tropical Deep House Music Chill Out Mix 2023 🍓 Chillout Lounge
URL: https://youtube.com/watch?v=h8uGUlZoGJI
Likes: None
Duration: 0 sec
----------------------------------------
Title: Nazareth Greatest Hits Full Album - Best Songs Nazareth Playlist 2024
URL: https://youtube.com/watch?v=E31cNEyhBu8
Likes: None
Duration: 5072 sec
----------------------------------------

```

**Comment by JuanBindez** [comment]
I understand, send it to the search branch
