### ISSUE TITLE
How to use a private socks5 proxy in pytubefix?

### ISSUE THREAD

**Issue by florestdev** [JuanBindez/pytubefix#271]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

# put your code here

```

__________
**Expected behavior**

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: [Your Operating System and Version]
 - Python Version [x.y.z]
 - Pytubefix Version [x.y.z]

__________
**Additional context**

**Comment by JuanBindez** [comment]
```python
from pytubefix import YouTube

proxy = {
    "http": "socks5://proxy_address",
    "https": "socks5://proxy_address"
    }

url = "url"
 
yt = YouTube(url, proxies=proxy)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()

```

**Comment by florestdev** [comment]
> 
> ```python
> from pytubefix import YouTube
> 
> proxy = {
>     "http": "socks5://proxy_address",
>     "https": "socks5://proxy_address"
>     }
> 
> url = "url"
>  
> yt = YouTube(url, proxies=proxy)
> print(yt.title)
>  
> ys = yt.streams.get_highest_resolution()
> ys.download()
> 
> ```

Thanks. But I want to know how use private proxies with username and password. How can I do this?

**Comment by deeffest** [comment]
with a username and password
```
{
    "http": "socks5://user:pass@socks5.example.com:1080",
    "https": "socks5://user:pass@socks5.example.com:1080"
}
```
without
```
{
    "http": "socks5://socks5.example.com:1080",
    "https": "socks5://socks5.example.com:1080"
}
```

**Comment by florestdev** [comment]
> with a username and password
> ```
> {
>     "http": "socks5://user:pass@socks5.example.com:1080",
>     "https": "socks5://user:pass@socks5.example.com:1080"
> }
> ```
> without
> ```
> {
>     "http": "socks5://socks5.example.com:1080",
>     "https": "socks5://socks5.example.com:1080"
> }
> ```

Sorry, but that's exactly what I did. What should I do if I get the error "The destination computer rejected the connection request"?

**Comment by deeffest** [comment]
I had the same error when using a free VPN, YouTube itself worked without problems, but I couldn't download anything through pytube. After buying a paid VPN/Proxy everything worked as it should.

**Comment by florestdev** [comment]
> I had the same error when using a free VPN, YouTube itself worked without problems, but I couldn't download anything through pytube. After buying a paid VPN/Proxy everything worked as it should.

My proxy is private. What can I do?

**Comment by deeffest** [comment]
Does YouTube itself work through your proxy?

**Comment by florestdev** [comment]
> Does YouTube itself work through your proxy?

Yeah, bro. It works.

**Comment by deeffest** [comment]
I suggest you try changing socks5 to http(s), in most cases you can do this on the website of the proxy you bought. And I want to make sure, are you using an IPv4 proxy?

**Comment by florestdev** [comment]
> I suggest you try changing socks5 to http(s), in most cases you can do this on the website of the proxy you bought. And I want to make sure, are you using an IPv4 proxy?
Okey. I will change a protocol right now. Yes, I use IPv4.
