### ISSUE TITLE
Is it never downloaded in virtual machine?

### ISSUE THREAD

**Issue by jjikkobro** [JuanBindez/pytubefix#272]
_________
**Describe the bug**
I’ve tried using proxies and tokens, but I still couldn’t get the video to download on the virtual machine. If anyone has successfully managed to do this in a VM, please let me know. I don’t want to waste any more time on this.

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube

proxies = {
                        'http': f'socks5://{username}:{password}@{proxy_ip}:{proxy_port}',
                        'https': f'socks5://{username}:{password}@{proxy_ip}:{proxy_port}'
                    }
             
visitor_data, po_token = await self.get_tokens()
yt = YouTube(url, proxies=proxies, use_po_token=True, po_token_verifier=(visitor_data, po_token))

```

__________
**Expected behavior**

**JUST DOWNLOAD**

__________
**VM(please complete the following information):**
- Platfrom Azure
 - OS: Linux
 - Python Version Python: 3.8.10 (default, Sep 11 2024, 16:02:53) 
 - Pytubefix Version 7.4.0

**Comment by jhanley-com** [comment]
Since you are using a proxy, you will need to do the debugging and create something that clearly indicates a problem with PyTubeFix. You do not even describe the behavior, error messages, etc. We do not have magic crystal balls.

**Comment by jjikkobro** [comment]
> Since you are using a proxy, you will need to do the debugging and create something that clearly indicates a problem with PyTubeFix. You do not even describe the behavior, error messages, etc. We do not have magic crystal balls.

Got it. First, I had to follow the instructions from this link to enable YouTube downloads on my cloud machine: https://github.com/JuanBindez/pytubefix/pull/209.

I used the po_token_generator, written in Python, that you're familiar with to generate and apply the token, but I'm still getting a "detected as bot" error. When I was using youtubeTranscriptApi, I was able to solve the issue by using a socks5 proxy. I tried using both a paid proxy and the po_token in a similar way this time, but I'm still getting the "detected as bot" error.

What I'm wondering is: is it simply not possible to use YouTube download on a cloud machine at all? Or has no one been successful with any method so far?

**Comment by NannoSilver** [comment]
> > Since you are using a proxy, you will need to do the debugging and create something that clearly indicates a problem with PyTubeFix. You do not even describe the behavior, error messages, etc. We do not have magic crystal balls.
> 
> Got it. First, I had to follow the instructions from this link to enable YouTube downloads on my cloud machine: #209.
> 
> I used the po_token_generator, written in Python, that you're familiar with to generate and apply the token, but I'm still getting a "detected as bot" error. When I was using youtubeTranscriptApi, I was able to solve the issue by using a socks5 proxy. I tried using both a paid proxy and the po_token in a similar way this time, but I'm still getting the "detected as bot" error.
> 
> What I'm wondering is: is it simply not possible to use YouTube download on a cloud machine at all? Or has no one been successful with any method so far?


Seems the potoken is IP dependent. If you are using a proxy, then the potoken must be for the proxy IP, rather than your VPS cloud machine IP.


Another way is to to use proxy without potoken. For that you have to find a proxy that is not detected as  bot. 

The so called "residential" proxies have a higher probability that will not be detected as bot. But they are very expensive.

You can also check the proxy at [https://ipinfo.io/](https://ipinfo.io/). If the proxy IP is **false** for all purple indicators (vpn, tor, proxy, relay, hosting), then there is a good chance it will not be detected as bot.
![image](https://github.com/user-attachments/assets/071c8e29-8d19-4931-8c39-c4c80ba23c02)




But the rule is that there is no rule. Have to keep replacing/changing the proxy until find one that works. And a proxy that is working today may be detected as bot tomorrow.

**Comment by felipeucelli** [comment]
The main purpose of passing PO Token is to help prevent getting blocked (if on non-DC IP) and allow formats from web clients to work.

If you are being detected as a bot even after passing the PoToken, there are only two alternatives:
1. Log in with use_oauth (and risk getting your account banned)

2. Use a proxy to change your IP address.

If even after these attempts you continue to be detected, unfortunately there is nothing we can do.

See some references about PoToken and blocking in cloud applications:

[https://github.com/LuanRT/BgUtils/issues/7](https://github.com/LuanRT/BgUtils/issues/7)
[https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990](https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990)
[https://github.com/yt-dlp/yt-dlp/issues/11053](https://github.com/yt-dlp/yt-dlp/issues/11053)

**Comment by NannoSilver** [comment]
Here is a code to obtain poToken programmatically in python:

https://github.com/iv-org/youtube-trusted-session-generator

I did not tested.

**Comment by jjikkobro** [comment]
I could download with **use_oauth** param without any other params.
I think that there is no other way to download on cloud machine now.

**Comment by felipeucelli** [comment]
Maybe I discovered something, I compared the programmatically generated PoToken from some tools and it seems that the one in this repository [https://github.com/LuanRT/BgUtils](https://github.com/LuanRT/BgUtils), generates the PoToken differently, they are larger and more similar to the one generated by the official YouTube client.

> Here is a code to obtain poToken programmatically in python:
> 
> https://github.com/iv-org/youtube-trusted-session-generator
> 
> I did not tested.

During my testing, this tool returned fake PoTokens, it seems that if the page doesn't load in time, it doesn't return the correct token.

**Comment by JuanBindez** [comment]
I'm going to upload a branch called PoToken, if anyone can test it I'd appreciate it, if there's something wrong, if the tokens don't work let me know, I'll remove the branch or try to improve it so I can test it, just use the code below:

```python
from pytubefix import PoToken

po = PoToken()

print("PoToken:", po.get_potoken())
```
