### ISSUE TITLE
Cannot retrieve the URL for kids' videos.

### ISSUE THREAD

**Issue by MimuraKyosuke** [JuanBindez/pytubefix#298]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
Kids' videos can be viewed without logging in, but as shown below, the URL cannot be retrieved. 
ex) https://www.youtube.com/watch?v=CfUlR_ghqXk

__________
**code that was used that resulted in the bug**

```python
import sys
from pytubefix import YouTube

if len(sys.argv) > 1:
    video_id = sys.argv[1]
else:
    print("Usage: python script.py <video_id>")
    sys.exit(1)

video_url = f'https://www.youtube.com/watch?v={video_id}'
yt = YouTube(video_url)
best_url = yt.streams.get_highest_resolution().url
print(best_url)
```

```
$ python3 get_url.py CfUlR_ghqXk
Traceback (most recent call last):
  File "/home/myname/ytdl_project/get_url.py", line 18, in <module>
    best_url = yt.streams.get_highest_resolution().url
  File "/home/myname/.local/lib/python3.10/site-packages/pytubefix/__main__.py", line 632, in streams
    self.check_availability()
  File "/home/myname/.local/lib/python3.10/site-packages/pytubefix/__main__.py", line 339, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytubefix.exceptions.VideoUnavailable: CfUlR_ghqXk is unavailable
```

__________
**Expected behavior**
I want to retrieve the URL.

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04.3 LTS]
 - Python Version [3.10.12]
 - Pytubefix Version [8.1.1]

__________
**Additional context**

**Comment by deeffest** [comment]
#285 After changing the client (e.g. to MWEB) has anything changed?

**Comment by MimuraKyosuke** [comment]
I was able to retrieve the URL using MWEB.
Thank you!

**Comment by dhairyapatel1506** [comment]
I don't think switching to MWEB fixes the issue anymore. Can someone verify?
