### ISSUE TITLE
[CONTRIBUTORS]

### ISSUE THREAD

**Issue by JuanBindez** [JuanBindez/pytubefix#3]
The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!

**Comment by ElsevarAsadov** [comment]
> The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!

Hi Juan Do you interest interactive web based GUI for users to download videos easily? i wanna make it i f u interest this kinda stuff

**Comment by JuanBindez** [comment]
> > The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!
> 
> Hi Juan Do you interest interactive web based GUI for users to download videos easily? i wanna make it i f u interest this kinda stuff

Hi Elsevar, I've already thought about something like this but I would need to deploy the application somewhere, that's why I haven't done it yet, as it might incur a cost, if you know of somewhere that we can do this deployment without financial cost let me know, Maybe we can do something like this together

**Comment by ElsevarAsadov** [comment]
> > > The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!
> > 
> > 
> > Hi Juan Do you interest interactive web based GUI for users to download videos easily? i wanna make it i f u interest this kinda stuff
> 
> Hi Elsevar, I've already thought about something like this but I would need to deploy the application somewhere, that's why I haven't done it yet, as it might incur a cost, if you know of somewhere that we can do this deployment without financial cost let me know, Maybe we can do something like this together

ofc we can. we can create local server in client and serve GUI most of python packages does it. (look auto-py-to-exe).

**Comment by JuanBindez** [comment]
> > > > The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!
> > > 
> > > 
> > > Hi Juan Do you interest interactive web based GUI for users to download videos easily? i wanna make it i f u interest this kinda stuff
> > 
> > 
> > Hi Elsevar, I've already thought about something like this but I would need to deploy the application somewhere, that's why I haven't done it yet, as it might incur a cost, if you know of somewhere that we can do this deployment without financial cost let me know, Maybe we can do something like this together
> 
> ofc we can. we can create local server in client and serve GUI most of python packages does it. (look auto-py-to-exe).i can create a dedicated eletronjs application but it will make package size so big. we can distribute it as a additional branch but i think it is a little bit overworking

I made a project similar to what you're talking about, see if it's something like this -> https://github.com/JuanBindez/DYGTube-Downloader

**Comment by callumosborne** [comment]
I have built a python web-app downloader, I can share the repo, it will download both youtube and spotify links by converting the spotify playlist into a list of youtube tracks, happy to share if someone wants to host it

**Comment by JuanBindez** [comment]
> I have built a python web-app downloader, I can share the repo, it will download both youtube and spotify links by converting the spotify playlist into a list of youtube tracks, happy to share if someone wants to host it

share with us

**Comment by callumosborne** [comment]
I need to clean up and remove some bits but I will create a repo for the backend and frontend

**Comment by callumosborne** [comment]
> > I have built a python web-app downloader, I can share the repo, it will download both youtube and spotify links by converting the spotify playlist into a list of youtube tracks, happy to share if someone wants to host it
> 
> share with us

I need to clean up and remove some bits but I will create a repo for the backend and frontend

**Comment by poneoneo** [comment]
> > > The aim of Pytubefix is ​​to be updated faster so that I don't have to wait a long time, I waited for Pytube to be updated but it took a long time, so I had the initiative to make Pytubefix so that my application wouldn't stop, so this It helps me and helps other developers. If you would like to contribute, you are welcome!
> > 
> > 
> > Hi Juan Do you interest interactive web based GUI for users to download videos easily? i wanna make it i f u interest this kinda stuff
> 
> Hi Elsevar, I've already thought about something like this but I would need to deploy the application somewhere, that's why I haven't done it yet, as it might incur a cost, if you know of somewhere that we can do this deployment without financial cost let me know, Maybe we can do something like this together

hey im interessting to make this project with both of you i know to make website with django and i also know how to deploy it as free are you ready ?

**Comment by andrebore04** [comment]
Hi, I wanted to share a GUI implementation of this library I made with CustomTkinter.
This is the repo: https://github.com/andrebore04/PyTubeFX
