### ISSUE TITLE
Error in downloading videos

### ISSUE THREAD

**Issue by Shaadalam9** [JuanBindez/pytubefix#303]
**Describe the bug**
It looks like there in some error in the pytubefix package. I tried to search it on google to fix this bug, but the old suggestion doesn't match with the updated pytubefix especially "cipher.py".

Error occurred regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*
__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress

def download_video_with_resolution(video_ids, resolutions=["2160p", "1440p", "1080p", "720p", "480p", "360p"],
                                   output_path="."):
    try:
           
            youtube_url = f'https://www.youtube.com/watch?v={vid}'
            youtube_object = YouTube(youtube_url, on_progress_callback=on_progress)
            for resolution in resolutions:
                video_streams = youtube_object.streams.filter(res=f"{resolution}")
                if video_streams:
                    logger.debug(f"Found video {vid} in {resolution}.")
                    break


```

__________
**Expected behavior**
The video should have started to download in my local system, but I am getting this error.

__________
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python Version 3.9.19
 - Pytubefix Version 8.2.0

**Comment by JuanBindez** [comment]
show full error output

**Comment by Shaadalam9** [comment]
The only output I am getting is 
```
(dashcam) xxx@xxxxx:~/repos/xxxx$ python3 download_videos.py 
2024-10-29 12:17:09,482 - INFO     - __main__ - Download of videos started.
2024-10-29 12:17:09,484 - ERROR    - __main__ - Error occurred regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*.
2024-10-29 12:17:09,484 - INFO     - __main__ - Processed 0 videos.

```

**Comment by Shaadalam9** [comment]
What do you mean by "what is the id?" ?
