### ISSUE TITLE
.get_audio_only() results in a 48kbps quality file, not the highest audio quality by default

### ISSUE THREAD

**Issue by TyrelCB** [JuanBindez/pytubefix#321]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**

Instead of the expected 128kbps file, all .get_audio_only() streams are 48kbps

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "url" # any 
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_audio_only()
ys.download(mp3=True)
```

__________
**Expected behavior**

128kbps AAC

__________
**Screenshots**

Not needed

__________
**Desktop (please complete the following information):**
 - OS: Fedora 41
 - Python Version 3.13.0
 - Pytubefix Version 8.3.2

__________
**Additional context**

This will pull pull the highest quality audio stream

```
yt.streams.filter(only_audio=True, audio_codec="mp4a.40.2").order_by('abr')[-1].download()
```

**Comment by JuanBindez** [comment]
try without the mp3

**Comment by NannoSilver** [comment]
Also, be aware that there are no MP3 audio files available at Youtube.
If you want in MP3, you have to convert it.

The `mp3=True` option of pytubefix does not provide in real MP3 codec, but only rename the extension to MP3.

**Comment by TyrelCB** [comment]
guys the fix is specifying an audio codec, this provides 128kbps AAC, which is the most versitile: 

```
yt.streams.filter(only_audio=True, audio_codec="mp4a.40.2").order_by('abr')[-1].download()
```

I'll submit a PR to modify the .get_audio_only() method
