### ISSUE TITLE
mp3=True not resulting in error free file.

### ISSUE THREAD

**Issue by KS-HTK** [JuanBindez/pytubefix#325]
**Describe the bug**
Using `yt.streams.get_audio_only().download(mp3=True)` does not produce issue free mp3 file.
The file can be played back but the id3 metadata is broken somehow. Neither eyed3 nor Windows explorer can add or modify the metadata of the downloaded file.

__________
**code that was used that resulted in the bug**

```python
import os
from pytubefix import YouTube
from pytubefix.exceptions import AgeRestrictedError
import eyed3

yt = YouTube("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
yt.streams.get_audio_only().download(mp3=True, output_path="music", filename="test")
audpath = os.path.join("music", "test.mp3")
file = eyed3.load(audpath)
if file is None:
  print("Error Could not load audiofile")
```

__________
**Expected behavior**
eyed3 should be able to load the file as it should be an mp3 mime-type.

converting from downloaded mp4 to mp3 using moviepy and then using eyed3 to load works fine.

__________
**Desktop (please complete the following information):**
 - OS: Win 11 Pro 24H2
 - Python Version [3.10.11]
 - Pytubefix Version [8.3.2]

**Comment by JuanBindez** [comment]
it is not corrupted, in fact it is not a real mp3

**Comment by JuanBindez** [comment]
so it returns None

**Comment by JuanBindez** [comment]
```bash
ExifTool Version Number         : 12.65
File Name                       : Rick Astley - Never Gonna Give You Up (Official Music Video).mp3
Directory                       : .
File Size                       : 3.4 MB
File Modification Date/Time     : 2024:11:14 22:11:54-03:00
File Access Date/Time           : 2024:11:14 22:18:44-03:00
File Inode Change Date/Time     : 2024:11:14 22:20:38-03:00
File Permissions                : -rw-rw-r--
File Type                       : M4A
File Type Extension             : m4a
MIME Type                       : audio/mp4
Major Brand                     : Unknown (dash)
Minor Version                   : 0.0.0
Compatible Brands               : iso6, mp41
Movie Header Version            : 0
Create Date                     : 2024:05:30 05:43:29
Modify Date                     : 2024:05:30 05:43:29
Time Scale                      : 44100
Duration                        : 0:03:32
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 2
Track Header Version            : 0
Track Create Date               : 2024:05:30 05:43:29
Track Modify Date               : 2024:05:30 05:43:29
Track ID                        : 1
Track Duration                  : 0:03:32
Track Layer                     : 0
Track Volume                    : 100.00%
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2024:05:30 05:43:29
Media Modify Date               : 2024:05:30 05:43:29
Media Time Scale                : 44100
Media Duration                  : 0:03:32
Media Language Code             : eng
Handler Description             : ISO Media file produced by Google Inc.
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Balance                         : 0
Handler Type                    : Metadata
Handler Vendor ID               : Apple
Encoder                         : Google
Movie Fragment Sequence         : 22
Media Data Size                 : 38539
Media Data Offset               : 3395066
Avg Bitrate                     : 128 kbps


```

**Comment by KS-HTK** [comment]
Well I would consider an incorrect file extensions as a corruption of a file. It confuses and lets one believe there to be support for features that are not there. Why even save it as mp3 if it isn't even an mp3?

In my opinion it should either be a proper conversion or the flag should be removed/renamed to audioOnly. Because from the exif it looks to be m4a (mp4 Audio container if I understand it correclty). And it should save to m4a or mp4 but not mp3.

**Comment by JuanBindez** [comment]
You just had to look at the documentation, it explains that the codec is mp4, before the audios didn't have the correct extension that's why this feature was added, currently it saves the audios with the correct extension which is .m4a, just don't use it o mp3=True.

**Comment by JuanBindez** [comment]
> Well I would consider an incorrect file extensions as a corruption of a file. It confuses and lets one believe there to be support for features that are not there. Why even save it as mp3 if it isn't even an mp3?
> 
> In my opinion it should either be a proper conversion or the flag should be removed/renamed to audioOnly. Because from the exif it looks to be m4a (mp4 Audio container if I understand it correclty). And it should save to m4a or mp4 but not mp3.

some people who have not been following the library since the beginning are having difficulty understanding why some resources exist here, if they exist there is a reason, these resources are being fixed gradually, for example in version 8.2.0 https://github .com/JuanBindez/pytubefix/releases/tag/v8.2.0 the m4a extension of the correct audio codec was fixed, which was not done in pytube, the audios were downloaded as mp4, that is, the library is in constant development where resources as mp3 will no longer be necessary, if you don't like pytubefix, just use pytube.

**Comment by KS-HTK** [comment]
> You just had to look at the documentation, it explains that the codec is mp4, before the audios didn't have the correct extension that's why this feature was added, currently it saves the audios with the correct extension which is .m4a, just don't use it o mp3=True.

The [documentation](https://pytubefix.readthedocs.io/en/latest/user/mp3.html) states that using `mp3=True` will save it with extension `.mp3`. I could not find any Information on why this might not have id3 matadata support and that is precisely why I created this Issue. 
Only the title of the page states `(MPEG-4 AAC audio codec)`, which to me did not register as it is mp4 and not supporting all mp3 features immediately.
If it is know, and by design that is fine by me but it might help to add a little note to the Documentation on what is actually happening, for people like me, who do not work with MPEG formats all the time.


> some people who have not been following the library since the beginning are having difficulty understanding why some resources exist here, if they exist there is a reason, these resources are being fixed gradually, for example in version 8.2.0 the m4a extension of the correct audio codec was fixed, which was not done in pytube, the audios were downloaded as mp4, that is, the library is in constant development where resources as mp3 will no longer be necessary, if you don't like pytubefix, just use pytube.

This misses the mark of why I created the issue. I do understand that these libraries grow gradually and try to improve on previous version and implementations without breaking every implementation. Which is why i switched from pytube to pytubefix, as pytube is not really actively maintained.
I created the Issue to suggest a fix/change for something that I had an issue with and thought might be a bug.\
So please take no offense by an Issue as it might just be to help highlight something the author of said issue did not quite understand.
And honestly: Thank you for the fast responses and maintaining a library I enjoy to use.

**Comment by JuanBindez** [comment]
Anyway, I'm sorry if it seemed rude, it's just that sometimes I have to repeat the same questions, and in the case of mp3 I'm already removing the extension for the next version and marking it as deprecated, to remove it once and for all in the future, because there are people who still use,

**Comment by JuanBindez** [comment]
but it's good that you commented, because other people probably don't understand and I've been putting off removing this feature for some time, it will be good to avoid this type of confusion, thanks for your contribution.
