### ISSUE TITLE
Youtube changed something on "https://www.youtube.com/youtubei/v1/player?prettyPrint=false" url

### ISSUE THREAD

**Issue by akirapix** [JuanBindez/pytubefix#327]
I suppose Youtube changed the way of accessing this URL
_https://www.youtube.com/youtubei/v1/player?prettyPrint=false_
causing a 400 error

if i try to copy/paste this url on the browser it says:

405. That’s an error.
The request method GET is inappropriate for the URL /youtubei/v1/player. 
That’s all we know.

this behaviour changed more or less yesterday, and only when using allow_oauth_cache=True and use_oauth=True

to reproduce the error i used simply:

from pytubefix import YouTube

yt = YouTube(<youtube-url>, allow_oauth_cache=True, use_oauth=True) 
stream = yt.streams.filter(only_audio=True).order_by('abr').desc().first()
 
this piece of code was working without any errors since a month, but suddenly stopped giving me a 400 error

code is working on:
- OS: Linux,OSX and also under Docker
- Python 3.9.11
- pytubefix 8.3.2

**Comment by angela-gentile** [comment]
Same problem too

**Comment by rockfarmor** [comment]
Same issue

**Comment by akirapix** [comment]
> Same issue, setting allow_oauth_cache and use_oauth to False resolves the issue, besides not being able to download some videos due to not being authenticated

yeah the same for me. i need to make it work  **allow_oauth_cache** and **use_oauth** set to True

**Comment by JuanBindez** [comment]
The version that corrects this has been released, 8.4.1 and taking advantage of the use of oauth, I made a PR to reset the cache, if you can leave your opinions on whether or not I should launch it, if it will help... I tested it and it made it a lot easier , if you want to test this in the "reset_cache" branch, see the PR on how to use it -> https://github.com/JuanBindez/pytubefix/pull/333
