### ISSUE TITLE
Not working in AWS or Oracle instances

### ISSUE THREAD

**Issue by timbrowning327** [JuanBindez/pytubefix#342]
My local machine runs the code no problem and can scrape the transcript but running it on the ec2 instance it returns null. Here is the code -

def get_youtube_transcript(video_url):
try:
yt = YouTube(video_url, on_progress_callback=on_progress)
transcript = yt.captions['a.en'].generate_srt_captions()
cleaned_transcript = re.sub(r'\d+\s*\n|\d{2}:\d{2}:\d{2},\d{3}\s*-->\s*\d{2}:\d{2}:\d{2},\d{3}\s*\n', '',
transcript)
cleaned_transcript = " ".join([line.strip() for line in cleaned_transcript.splitlines() if line.strip()])
return cleaned_transcript
except Exception as e:
print(f"Error fetching transcript for video {video_url}: {str(e)}")
return None

Is it blocked on EC2? This does work in Google Cloud platform

**Comment by timbrowning327** [comment]
Can this feature be added to this python library

**Comment by NannoSilver** [comment]
> My local machine runs the code no problem and can scrape the transcript but running it on the ec2 instance it returns null. Here is the code -
> 
> def get_youtube_transcript(video_url): try: yt = YouTube(video_url, on_progress_callback=on_progress) transcript = yt.captions['a.en'].generate_srt_captions() cleaned_transcript = re.sub(r'\d+\s*\n|\d{2}:\d{2}:\d{2},\d{3}\s*-->\s*\d{2}:\d{2}:\d{2},\d{3}\s*\n', '', transcript) cleaned_transcript = " ".join([line.strip() for line in cleaned_transcript.splitlines() if line.strip()]) return cleaned_transcript except Exception as e: print(f"Error fetching transcript for video {video_url}: {str(e)}") return None
> 
> Is it blocked on EC2? This does work in Google Cloud platform


Likely detected as BOT and blocked by Youtube.

Search the archived issues and also look here:
https://github.com/JuanBindez/pytubefix/pull/209
