### ISSUE TITLE
Is it possible to redirect downlod() to stdout?

### ISSUE THREAD

**Issue by mezantrop** [JuanBindez/pytubefix#348]
Subj.
Thanks in advance.

**Comment by felipeucelli** [comment]
You can create a custom function and pass it to `on_progress_callback`.

See an example from the [documentation](https://pytubefix.readthedocs.io/en/latest/):

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = input("URL >")

yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()
```

Here a custom function from Pytubefix itself was used.

**Comment by JuanBindez** [comment]
It seems like he wants to redirect the download, for example directly to the console or a data stream (stream) without saving to disk, what I understood was this.

**Comment by JuanBindez** [comment]
@mezantrop I'll try to do it, I've already opened a branch to do it

**Comment by mezantrop** [comment]
@JuanBindez, yes, this would be a nice feature, I'd use it to stream into ASCII converter to use it later as a source for the terminal screensaver.

**Comment by mezantrop** [comment]
Looks good! Thank you!
