### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by lugamecooper** [JuanBindez/pytubefix#35]
when i download a playlist i have this error:
![image](https://github.com/JuanBindez/pytubefix/assets/123462698/24eeeb6d-0c9b-4001-9b6b-5952e7e6561d)
it's came when i downloads more of one videos and it's crash when i get the title

 - OS: windows 10
 - Version: pytubefix 1.13.3

this is the function :
def téléchargement_playlist(self):
        error = False
        try:
            playlist = Playlist(self.url)
        except Exception as er:
            print(er)
            print("l'url donnée n'est pas valide ou correct\n",
                  "the given url is not correct")
            return None
        for video in playlist.videos:
            if video.age_restricted:
                print(f"la vidéo {video.title} est soumise à une limite d'âge\n",
                      f"the video {video.title} is subject to an age limit")
            else:
                title = video.title
                title = title.replace("\n","")
                title = title.replace("\\","")
                title = title.replace("/","")
                video.title = title
                try:
                    if self.type_téléchargement:
                        video.streams.get_audio_only().download(self.paht,title,mp3=True)
                    else:
                        video.streams.get_highest_resolution().download(self.paht,title,mp3=False)
                    print(f"le téléchargement de {title} est fini\n",
                          f"the download of {title} is finished")
                except Exception as er:
                    print(er)
                    print(f"une erreur est survenue pour la vidéo {title}\n",
                          f"an error has occurred for the video {title}")
                    error = True
        if not error:
            system("cls")

if you want i can give the entire code

**Comment by yannickErp** [comment]
Having this issue too since yesterday, on mac with pytubefix 1.13.3

**Comment by NannoSilver** [comment]
Since around 10 days ago I am also getting a relevant number of `HTTP Error 400: Bad Request` for various tasks with pytubefix.
If the operation is repeated, then it works in most of the cases, but in some cases have to repeat 3 or 4 times to get the task done.
My system is running pytubefix 1.13.3 at an Ubuntu 20.04 server.

**Comment by lugamecooper** [comment]
thanks you, who you can reapeat the task ?

**Comment by JuanBindez** [comment]
try pytubefix==2.0rc2
