### ISSUE TITLE
yt.views and yt.publish_date not returning anything

### ISSUE THREAD

**Issue by Concept211** [JuanBindez/pytubefix#350]
The `views` and `publish_date` properties not returning anything. Tested on multiple videos URLs and it's always the same issue. Maybe YouTube changed their json payload and it's now they're named something different?

**Comment by Mak5er** [comment]
yt.author return unknown also

**Comment by NannoSilver** [comment]
I just tested with pytubefix 8.5.1 and everything is working normally.

Tested code:
```
from pytubefix import YouTube

video_url = "http://youtube.com/watch?v=mZkHwI7cX4Y"

yt = YouTube(video_url)


print(yt.title)
print(yt.author)
print(yt.channel_id)
print(yt.views)
print(yt.publish_date)
```


Output:
```
Joe Rogan Experience #2228 - Josh Dubin
PowerfulJRE
UCzQUP1qoWDoEbmsQxvdjxgQ
692386
2024-11-13 10:00:34-08:00
```

**Comment by Concept211** [comment]
I believe this must be a regional issue (the VPS I run my code from is physically based out of Germany). This is the exact same issue as we had before here: https://github.com/JuanBindez/pytubefix/issues/138

It seems that the data embedded in the YouTube page that you're scraping from is different outside of the US. From the **extract.py** file I did a console print of `watch_html` and below is what the html looks like. You'll notice the property names don't match up with what your code is parsing. Again, see issue #138 for reference.

This is why for many users of pytubefix it's not working for them because they are outside of the United States.

Here is the html source for reference:
https://gist.github.com/Concept211/72d447a2f8efc9af0f44f00e4084ab4d
