### ISSUE TITLE
New bug on pytubefix 8.5.1:   ".m4a" extension always added to all downloaded audio

### ISSUE THREAD

**Issue by NannoSilver** [JuanBindez/pytubefix#354]
This bug is present on pytubefix 8.5.1, but was not present on pytubefix 8.3.2.
Seems the bug was introduced at the same time the MP3 parameter was removed.

Code to test the bug:
```
from pytubefix import YouTube

youtube_episode_id = '3p6DEyF5LZM'

url = f'https://www.youtube.com/watch?v={youtube_episode_id}'
yt = YouTube(url)

stream = yt.streams.get_by_itag(140)
stream.download(filename=f'{youtube_episode_id}.m4a')
```

Expected outcome:
Download of the audio and save to a file named `3p6DEyF5LZM.m4a`

Actual outcome:
Downloaded file is saved under the name `3p6DEyF5LZM.m4a.m4a`

The additional `.m4a` extension breaks the back-compatibility with codes already running and also creates issues with other audio formats, such as **webm/opus**, that is the audio format for itag = 251

_______________________________________

 - OS: Windows 11
 - Python Version 3.9
 - Pytubefix Version 8.5.1

**Comment by JuanBindez** [comment]
Hi @NannoSilver, it's actually not a bung, I added this in that version intentionally, just remove the .m4a from your code, but I see that this will cause more problems like the one you are reporting

**Comment by JuanBindez** [comment]
Do you think most people will manually add extensions?

**Comment by JuanBindez** [comment]
There will be people not including the extension and they will come here saying that it has a bug because it doesn't have an extension

**Comment by NannoSilver** [comment]
> There will be people not including the extension and they will come here saying that it has a bug because it doesn't have an extension

I see. Will have problems in one or another way.

I think keep the back-compatibility is more important because otherwise will generate issues for most of the users as the library historical behavior is not adding any extension, and all developers added by themselves.

Maybe the extension `.m4a` can be added when the parameter `filename=` is not passed, that is, the user is not specifying any file name. But I think the implications are deeper and not simple like this.

Also to take in consideration, that not all audio files are downloaded in M4A format. There are other formats where the extension `.m4a` will not be appropriate; for `itag = 251` the file extension will be `.webm`

**Comment by JuanBindez** [comment]
I'll fix this

**Comment by JuanBindez** [comment]
see if it has improved v8.5.2

**Comment by NannoSilver** [comment]
> see if it has improved v8.5.2

Thank you for fixing, @JuanBindez!
I did some tests with version 8.5.2 and seems it is working properly for the purposes I use it.

**Comment by felipeucelli** [comment]
Hello @JuanBindez 

I found a small bug regarding this issue. The `.m4a` is only defined when requested for the file name, and this can generate errors, for example:

```python

url = 'https://www.youtube.com/watch?v=60ItHLz5WEA'

yt = YouTube(url)

s = yt.streams[20]

print(s.subtype)
print(s.default_filename)
print(s.subtype)
```
output

```bash
mp4
Alan Walker - Faded.m4a
m4a
```

This can break some applications if the developer needs to get the subtype first.

I also have to agree with @NannoSilver regarding the `.webm` extension being downloaded in `.m4a`, although most systems will be able to reproduce it. From personal experience, this can cause several errors on simpler devices and this can also occur with `.mp4` being renamed to `.m4a`.

I believe the best way for everyone is to download it in the original format provided by YouTube and the developer can rename or convert it to the format they need.

**Comment by JuanBindez** [comment]
> Hello [@JuanBindez](https://github.com/JuanBindez)
> 
> I found a small bug regarding this issue. The `.m4a` is only defined when requested for the file name, and this can generate errors, for example:
> 
> url = 'https://www.youtube.com/watch?v=60ItHLz5WEA'
> 
> yt = YouTube(url)
> 
> s = yt.streams[20]
> 
> print(s.subtype)
> print(s.default_filename)
> print(s.subtype)
> 
> output
> 
> mp4
> Alan Walker - Faded.m4a
> m4a
> 
> This can break some applications if the developer needs to get the subtype first.
> 
> I also have to agree with [@NannoSilver](https://github.com/NannoSilver) regarding the `.webm` extension being downloaded in `.m4a`, although most systems will be able to reproduce it. From personal experience, this can cause several errors on simpler devices and this can also occur with `.mp4` being renamed to `.m4a`.
> 
> I believe the best way for everyone is to download it in the original format provided by YouTube and the developer can rename or convert it to the format they need.

I will keep it as it is and will not change it anymore, the correct extension of the codec is m4a, and if you want to convert the developer converts it in the way you want in the same way you mentioned, that is, it is the same
