### ISSUE TITLE
I am new to this field. On my local machine code is running well.

### ISSUE THREAD

**Issue by Pksb755** [JuanBindez/pytubefix#378]
# 🛑 DO NOT REMOVE OR SKIP THIS ISSUE TEMPLATE 🛑  
Issues with incomplete or missing information will be **closed automatically**.

---

## 🐞 **Bug Description**  
I am new to this development field. On my local machine code is running well.
But when i run it into server it gives EOF error.
Youtube detected you as a Bot.
Or else how can i setup the server so youtube doesnot block and your code will run properly.
---

## 🔢 **Code Snippet**  
Include the minimal code snippet that reproduces the issue.  

```python
from pytubefix import YouTube
video_url = f"https://www.youtube.com/watch?v={video_id}"
logging.info(video_url)
yt = YouTube(video_url
# use_po_token=True
)
logging.info("yt",yt)
stream = yt.streams.get_highest_resolution().url
logging.info(f"URL Stream {stream}")
```

---

## 🎯 **Expected Behavior**  
Describe what you expected to happen instead of the observed behavior.  
Url Should be extracted.
---

## 📸 **Screenshots or Logs**  
If applicable, attach screenshots or logs that demonstrate the issue.  
(Use a service like [Pastebin](https://pastebin.com/) if the logs are too lengthy.)  

---

## 🖥️ **Environment Details**  
Fill in the details below about your setup:  
- **Operating System:** Ubuntu 22.04.4 LTS 
- **Python Version:** 3.10  
- **Pytubefix Version:** 8.8.1

---

## 📋 **Additional Context**  
Add any additional information or context that might help us resolve the issue.  

---

### ✅ **Checklist Before Submitting**  
- [ ] I have read the [contribution guidelines](https://github.com/JuanBindez/pytubefix/blob/main/Contributing.md).  
- [ ] I have verified that the issue exists in the latest version of the library.  
- [ ] I have included all necessary details to reproduce the bug.  

---

### 🚀 **Next Steps**  
Once submitted, we will triage the issue. Make sure to respond to follow-up questions to keep the process smooth.

**Comment by NannoSilver** [comment]
You have to implement poToken or use a proxy.
Search in past issues. There is a lot of information.

**Comment by Pksb755** [comment]
> You have to implement poToken or use a proxy. Search in past issues. There is a lot of information.
