### ISSUE TITLE
is MP3 Support available?

### ISSUE THREAD

**Issue by amohideen** [JuanBindez/pytubefix#379]
Hi,

I was trying to use the streams.get_audio_only() function, I tried to set the parameter to "mp3", and this would throw an error or exception. 
Here is my simple call streams.get_audio_only("mp3").

The function definition from Qery.py is def get_audio_only(self, subtype: str = "mp4") -> Optional[Stream]:

**Comment by NannoSilver** [comment]
MP3 support is not available at pytubefix for the simple reason that mp3 audio is not available to download from Youtube.
You have to implement your own converter to MP3 if that is what you need.
