### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by EbotRawley** [JuanBindez/pytubefix#381]
(venv) C:\Users\ebotr\Downloads\ty-down\downer>python ytDL.py
Unknown Video Error
Video ID: 40Atg8bd8a0
Status: OK
Reason: This live event has ended.
Developer Message: Unknown video status
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide the above log output.

**Comment by JuanBindez** [comment]
please do not ignore the template
