### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by rgryta** [JuanBindez/pytubefix#4]
Cool project - thought of doing a similar thing myself at some point in the past.

Two things I'd suggest - can do them quite quickly if you'd agree to them.
1. Upgrade project to pyproject.toml - newer distutils doesn't necessarity disable setup.py installations, but in case of pytubefix, pyproject.toml by itself would suffice. This would also mean changing some development dependencies - nothing major though.
2. CI/CD - Github Actions pipeline to automatically deploy to pypi? Setup is extremely easy actually.

If you'd like any of these two things, it'd take me less than one evening to submit a PR.

**Comment by JuanBindez** [comment]
> Cool project - thought of doing a similar thing myself at some point in the past.
> 
> Two things I'd suggest - can do them quite quickly if you'd agree to them.
> 
>     1. Upgrade project to pyproject.toml - newer distutils doesn't necessarity disable setup.py installations, but in case of pytubefix, pyproject.toml by itself would suffice. This would also mean changing some development dependencies - nothing major though.
> 
>     2. CI/CD - Github Actions pipeline to automatically deploy to pypi? Setup is extremely easy actually.
> 
> 
> If you'd like any of these two things, it'd take me less than one evening to submit a PR.

Hi, I liked the idea of ​​pyproject.toml, I just don't want CI/CD now, if you could do the PR I would be grateful.
