### ISSUE TITLE
Method Error

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [JuanBindez/pytubefix#51]
**Describe the bug**
When upgrading to any version beyond 2.0.0, I get a method error for `publish_date`

**To Reproduce**
pip install --upgrade pytubefix
run code
get error about yt.publish_date not having a method `strftime()`

pip uninstall pytubefix
pip install 'pytubefix==2.0.0'
run code
no error

**Expected behavior**
I would expect the method to not fail

**Screenshots**
https://imgur.com/a/hl7WrIk

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux release 9.3 (Plow)
 - Python Version 3.11.5
 - Pytubefix Version 2.0.0 // 3.0.0

**Comment by JuanBindez** [comment]
try

```python

from pytubefix import YouTube

video_url = 'https://www.youtube.com/watch?v=ou9SmvrsVz0'

yt = YouTube (video_url)

publish_date = yt.publish_date
print(publish_date)
```

**Comment by JuanBindez** [comment]
Here it worked perfectly, it is normal for some videos to not have the date and time available.

**Comment by thisguyshouldworkforus** [comment]
The issue was in `extract.py`. It was not returning a datetime object.  I submitted a PR to fix that.
version 2.0.0 was returning a datetime object

https://github.com/JuanBindez/pytubefix/pull/52
