### ISSUE TITLE
Youtube.description Can't get a video description

### ISSUE THREAD

**Issue by Friend-Xu** [JuanBindez/pytubefix#55]
**Describe the bug**
from pytubefix import YouTube
youtube = YouTube(url)
description = youtube.description
with open(description_path,"a+",encoding="utf-8") as f:
    f.write(description)

![9e13aa712584809cd2d345eb63bba49](https://github.com/JuanBindez/pytubefix/assets/106003880/15aaec3d-2460-4d7e-ad88-ee832513cc8f)

pytubefix 3.0.0
python 3.9.0

youtube.description  returned result is None

**Comment by JuanBindez** [comment]
update to latest version -> pytubefix==4.0.0
