### ISSUE TITLE
fix the WEB client

### ISSUE THREAD

**Issue by JuanBindez** [JuanBindez/pytubefix#59]
**Describe the bug**

Fix WEB Client, for when the ANDROID client stops working

**Comment by Concept211** [comment]
Is this related to "the following content is not available" error we're suddenly experiencing when trying to download the video?

![image](https://github.com/JuanBindez/pytubefix/assets/589002/3d2494fc-4f07-49de-8056-dba419ee86ef)

**Comment by JuanBindez** [comment]
If this is happening to you, update to the latest version of pytubefix
