### ISSUE TITLE
Add support for Nebula.tv

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [JuanBindez/pytubefix#60]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, this is a traditional feature request.

**Describe the solution you'd like**
I would like to have support for downloading from [Nebula.tv](https://nebula.tv), which is currently supported on [yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/nebula.py) ... being able to feed in a Nebula URL like I do YouTube, and have it offer similar options like `.download()` and `.resolution()` ... [I can just plug things into my template](https://github.com/thisguyshouldworkforus/mytube/blob/main/TEMPLATE.py) and go from there!

**Describe alternatives you've considered**
I have considered trying to bootstrap this myself, as I can get the JSON payload from [yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/nebula.py) using the `--dump-json` command line switch, and I think I can go from there, but I'm still a novice with Python, so that's a big ask for me -- but I'm willing to learn!

**Additional context**
yt-dlp supports this with their extractor, [here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/nebula.py) (_for reference_)

**Comment by JuanBindez** [comment]
I'm thinking about doing a separate project just for Nebula

**Comment by NannoSilver** [comment]
> I'm thinking about doing a separate project just for Nebula

I think that is a better idea, instead of merge into Pytubefix, that will make it more complex and harder to maintain.
