### ISSUE TITLE
"urllib.error.HTTPError: HTTP Error 403: Forbidden" on long videos

### ISSUE THREAD

**Issue by kleingulo** [JuanBindez/pytubefix#7]
Hi I'm trying to download some long videos from YouTube unfortunately it doesn't work and I get a 403 reply. For shorter videos it's working fine.

Python 3.11.2
pytubefix 1.5.0

Test code:

`#python`
`from pytubefix import YouTube`

`#short video works`
`video = YouTube('https://www.youtube.com/watch?v=CpI3LCSh7zw')`
`video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()`
`print('completed')`

`#long video doesn't`
`video = YouTube('https://www.youtube.com/watch?v=AgpWX18dby4')`
`video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()`
`print('completed')`

Any help?

**Comment by JuanBindez** [comment]
> Hi I'm trying to download some long videos from YouTube unfortunately it doesn't work and I get a 403 reply. For shorter videos it's working fine.
> 
> Python 3.11.2 pytubefix 1.5.0
> 
> Test code:
> 
> `#python` `from pytubefix import YouTube`
> 
> `#short video works` `video = YouTube('https://www.youtube.com/watch?v=CpI3LCSh7zw')` `video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()` `print('completed')`
> 
> `#long video doesn't` `video = YouTube('https://www.youtube.com/watch?v=AgpWX18dby4')` `video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()` `print('completed')`
> 
> Any help?

I haven't been able to solve it yet

**Comment by ElsevarAsadov** [comment]
> Hi I'm trying to download some long videos from YouTube unfortunately it doesn't work and I get a 403 reply. For shorter videos it's working fine.
> 
> Python 3.11.2 pytubefix 1.5.0
> 
> Test code:
> 
> `#python` `from pytubefix import YouTube`
> 
> `#short video works` `video = YouTube('https://www.youtube.com/watch?v=CpI3LCSh7zw')` `video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()` `print('completed')`
> 
> `#long video doesn't` `video = YouTube('https://www.youtube.com/watch?v=AgpWX18dby4')` `video.streams.filter(file_extension='mp4', adaptive=True).order_by("resolution").desc().first().download()` `print('completed')`
> 
> Any help?

Hi can you make clear 'long' how long video you mean?

**Comment by kleingulo** [comment]
The longest video I could download is 01:16:59 long and the shortest one that doesn't work is 01:21:21 long. So somewhere in between.

**Comment by rgryta** [comment]
Tested it a bit today and it looks like YT might have added some safety measure that blocks a generated streaming url if it's downloaded too quickly (at least that's my suspicion) - I'm basing that assumption on the fact that the block doesn't happen always on the same chunk download - it's around 1h 16min mark, but at a different chunk.

I have an idea for a workaround, but it IS a workaround:
1. Pass YouTube object as an optional(?) parent object to the Stream object along with it's designated itag
2. Then make the Stream.url property based on the YouTube.fmt_streams + attached itag
3. Once we encounter error code 403 - reset (clear _vid_info and _fmt_streams from YouTube) and restart downloading, but from where the previous download has stopped).

**Comment by DominiqueRT** [comment]
Hi, same issue

Code :
```
from pytubefix import YouTube, Stream
from pytubefix.cli import on_progress

url ="https://youtube.com/watch?v=6YiU1PLeifE"
yt = YouTube(url, on_progress_callback=on_progress)
ys:Stream = yt.streams.get_highest_resolution()
ys.download()
```

It generates exception :
```
  File "C:\Users\dom\PycharmProjects\youtube.monitor\test.py", line 7, in <module>
    ys.download()
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\streams.py", line 295, in download
    for chunk in request.stream(
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 155, in stream
    response = _execute_request(
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

It's a long video (8284s) but sometime it happens also for some short videos too. On short one, if you try again you'll finally get it.

Anyway, thanks for this project

**Comment by JuanBindez** [comment]
> Hi, same issue
> 
> Code :
> 
> ```
> from pytubefix import YouTube, Stream
> from pytubefix.cli import on_progress
> 
> url ="https://youtube.com/watch?v=6YiU1PLeifE"
> yt = YouTube(url, on_progress_callback=on_progress)
> ys:Stream = yt.streams.get_highest_resolution()
> ys.download()
> ```
> 
> It generates exception :
> 
> ```
>   File "C:\Users\dom\PycharmProjects\youtube.monitor\test.py", line 7, in <module>
>     ys.download()
>   File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\streams.py", line 295, in download
>     for chunk in request.stream(
>   File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 155, in stream
>     response = _execute_request(
>   File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
>     response = meth(req, response)
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
>     response = self.parent.error(
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error
>     return self._call_chain(*args)
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> ```
> 
> It's a long video (8284s) but sometime it happens also for some short videos too. On short one, if you try again you'll finally get it.
> 
> Anyway, thanks for this project

Hi, this video you tried is very long, but I'm going to do some tests to see if I can solve it.

**Comment by JuanBindez** [comment]
problem solved:

Youtube is blocking the connection because it cannot find a "real user", that is, it is trying to find the User-Agent that is used to provide information about the browser and the device. This only happens in longer videos.


To solve the problem, the device needs to be authenticated, Pytubefix already has this functionality, just pass some parameters, as in the code below that will use the long video.

```python

from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://www.youtube.com/watch?v=6YiU1PLeifE"

yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
ys = yt.streams.get_highest_resolution()

ys.download() # you will only get the request to authenticate once you download

```

this code will return this:

>> Please open https://www.google.com/device and input code XXX-XXX-XXX
>> Press enter when you have completed this step.


You must open the link in the browser and place the code that appeared and press enter in the terminal then this will start the download and will not return the error again, I hope this solves it for everyone.

**Comment by DominiqueRT** [comment]
Thanks but still the same exception : 
Authentification has been done.
It fails at @ 71.5%, 77.4%, 75.5% ... it depends on the trial.

```
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\streams.py", line 295, in download
    for chunk in request.stream(
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 155, in stream
    response = _execute_request(
  File "C:\Users\dom\AppData\Roaming\Python\Python310\site-packages\pytubefix\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
python-BaseException
```
Regards

**Comment by JuanBindez** [comment]
show the code you tested

**Comment by JuanBindez** [comment]
Remembering that authentication takes time to complete

**Comment by DominiqueRT** [comment]
> show the code you tested

```
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = "https://www.youtube.com/watch?v=6YiU1PLeifE"

yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback=on_progress)
ys = yt.streams.get_highest_resolution()
ys.download()
```

I tryied with computer reboot, disabling AdGuard Home (network software for blocking ads and tracking) but nothing change.

Thanks
