### ISSUE TITLE
Content not available (again)

### ISSUE THREAD

**Issue by Concept211** [JuanBindez/pytubefix#72]
It looks like Google/YouTube is blocking video downloads again. Do we need to spoof the requesting device maybe? I'm sure it's related to them only allowing the latest versions of their apps to load videos since they've been recently blocking access on older versions on Android.

![image](https://github.com/JuanBindez/pytubefix/assets/589002/4533e7b8-6058-40ce-8851-2a8a0547b34c)

**Comment by NannoSilver** [comment]
Download of audio with **itag = 140** is normal at my ending, with Pytubefix 5.2.0

**Comment by JuanBindez** [comment]
> It looks like Google/YouTube is blocking video downloads again. Do we need to spoof the requesting device maybe? I'm sure it's related to them only allowing the latest versions of their apps to load videos since they've been recently blocking access on older versions on Android.
> 
> ![image](https://private-user-images.githubusercontent.com/589002/326431771-4533e7b8-6058-40ce-8851-2a8a0547b34c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTkyNDYsIm5iZiI6MTcxNDM5ODk0NiwicGF0aCI6Ii81ODkwMDIvMzI2NDMxNzcxLTQ1MzNlN2I4LTYwNTgtNDBjZS04ODUxLTJhOGEwNTQ3YjM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxMzU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmRlMDI0NTdmM2EyZmRkYTFjMWQ1MzFjNzhhM2I0NzFlMDYyZDQ5MTEzMWViZDdhNTA0YjA5OTMyNzA5NmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_eBMrjsbHg6kUEdsF4jD2rhvDhl2zaGsG3jS_kn9NQ)

which version of pytubefix?

**Comment by Concept211** [comment]
Nevermind! Sorry about that. I thought I had upgraded to the latest version but I was still running the older 4.0 version. Everything is working great now, thanks :)
