### ISSUE TITLE
setuptools 67.4.0 is too high

### ISSUE THREAD

**Issue by pirate486743186** [JuanBindez/pytubefix#76]
**Is your feature request related to a problem? Please describe.**
Debian has setuptools 66.1.1, i forced it with that version and it seams to build fine.

**Describe the solution you'd like**
lower the required version to 66.1.1

**Comment by JuanBindez** [comment]
what we are using is working fine

**Comment by JuanBindez** [comment]
I understand, but as it's working well for now, let's keep it
