### ISSUE TITLE
IncompleteRead

### ISSUE THREAD

**Issue by jinhang87** [JuanBindez/pytubefix#77]
Hi, [JuanBindez](https://github.com/JuanBindez) I've installed pytubefix version 5.4.2. Here's the test code:

```
from pytubefix import YouTube

url = 'https://www.youtube.com/watch?v=xtQy5NTsHeE' # download failed

def test_YouTube():
    yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, client='WEB')
    video_stream = yt.streams.get_highest_resolution()

    output_path = r"./"
    video_title_file = "test.mp4"
    video_stream.download(output_path=output_path, filename=video_title_file, max_retries=5)
    print(f'Downloading video: {yt.title}')

if __name__ == '__main__': 
    test_YouTube()
```
Some YouTube links have this problem
Below is the error message I get when running the code:

```
Traceback (most recent call last):
  File "D:\code\python\project\some-reverse-works\examples\pytube\test_pytubefix_to_author.py", line 15, in <module>
    test_YouTube()
  File "D:\code\python\project\some-reverse-works\examples\pytube\test_pytubefix_to_author.py", line 11, in test_YouTube
    video_stream.download(output_path=output_path, filename=video_title_file, max_retries=5)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pytubefix\streams.py", line 325, in download
    for chunk in request.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pytubefix\request.py", line 185, in stream
    chunk = response.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 482, in read
    s = self._safe_read(self.length)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(435172 bytes read, 9002012 more expected)
```

**Comment by JuanBindez** [comment]
try using it without client="WEB", don't pass the client argument

**Comment by jinhang87** [comment]
The same error, my friend, is it related to the network, but it is normal for me to use other links

**Comment by Hetari** [comment]
I got this error too, but after waiting some time and rerunning the code, the video downloaded successfully. I don't know why! I think the problem is when the network goes slow suddenly while downloading the video!

**Comment by NannoSilver** [comment]
> I got this error too, but after waiting some time and rerunning the code, the video downloaded successfully. I don't know why! I think the problem is when the network goes slow suddenly while downloading the video!

I am frequently getting similar errors because of instability at Youtube servers.
Retrying is sometimes enough to get the file.

In other cases, the video is not ready to download because are lives that ended recently and Youtube did not finished the file processing yet. Even if the video is available accessing with the browser, it may not be available to download, and we have to wait a couple of hours; in rare cases, have to wait a few days.
