### ISSUE TITLE
Subtitle/caption tracks are no more fetched

### ISSUE THREAD

**Issue by Angel756984** [JuanBindez/pytubefix#81]
Hi, subtitle/caption tracks are no longer fetched. i've tested with my code and still with the first simple example on [read the docs](https://pytubefix.readthedocs.io/en/latest/user/captions.html).

```
from pytubefix import YouTube

yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
subtitles = yt.captions

print(subtitles)
```

Could you kindly explain the problem to me? Thank you.

**Comment by JuanBindez** [comment]
hello, try using this pytubefix==5.6rc2, where @felipeucelli made PR #85 that fixes this problem, and see if it is normalized and tell us if it is resolved.

**Comment by Angel756984** [comment]
It seems to work fine. Thank you!
