### ISSUE TITLE
Search Filters - filter results by language, length, ...

### ISSUE THREAD

**Issue by miraculix95** [JuanBindez/pytubefix#82]
Hi, it would be great to have search filters like the length of a video and the upload_date of a video.

For the search results I am getting:
Other than that: Is there a way to define my location (or does this work with VPN). Does it make a difference if I al logged into google?

Thanks :)

**Comment by CureSaba** [comment]
I specified gl for innertube but the result was the same.
┐(ﾟ～ﾟ)┌ｵﾃｱｹﾞ
