### ISSUE TITLE
Highest resolution is not highest resolution

### ISSUE THREAD

**Issue by LightslicerGP** [JuanBindez/pytubefix#89]
**Describe the bug**
When downloading a video using `video_stream = yt.streams.get_highest_resolution()` it saves the video as _not_ the highest resolution. The video I'm using is `https://youtu.be/Sz_YPczxzZc`

**To Reproduce**
```py
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://youtu.be/Sz_YPczxzZc"
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()
```

**Expected behavior**
To download the video in the highest resolution (in this case it should be 1080, not 720 or 640)

**Screenshots**
![image](https://github.com/JuanBindez/pytubefix/assets/63020072/0f7d1fe1-ae8a-4aa4-9ce0-cdae2f953ae8)

**Desktop (please complete the following information):**
 - OS: windows 11 home 22631.3593
 - Python Version 3.12.3
 - Pytubefix Version 5.4.2

**Comment by JuanBindez** [comment]
Have you tried the latest version 5.6?

**Comment by LightslicerGP** [comment]
![image](https://github.com/JuanBindez/pytubefix/assets/63020072/287112d4-b694-4b88-a871-b82e84909a7e)
Im on 5.6.3, reran it, and it still is at 720, not 1080
![image](https://github.com/JuanBindez/pytubefix/assets/63020072/2def3bdf-092c-4da4-9612-88abd8c8a331)
![image](https://github.com/JuanBindez/pytubefix/assets/63020072/3f2e0481-af2b-4a98-b39e-233f86f321ef)

**Comment by felipeucelli** [comment]
YouTube uses a streaming technique called Dynamic Adaptive Streaming over HTTP (DASH), this implies how streams are provided, in this case, progressive streams provide audio and video in a single file, while adaptive provides the audio and video in separate files.

ANDROID-based clients provide progressive streams in 360p and 720p resolution, WEB clients provide only 360p progressives, and IOS clients provide only adaptive streams.

The `get_highest_resolution()` and `get_lowest_resolution()` methods will only return progressive streams.

If you want higher quality videos, you can manually filter the higher quality streams, then download the audio and merge them using, for example, ffmpeg.
