### ISSUE TITLE
New Regex ERROR: 91mget_throttling_function_name: could not find match for multiple [0m   <class 'pytubefix.exceptions.RegexMatchError'>

### ISSUE THREAD

**Issue by NannoSilver** [JuanBindez/pytubefix#93]
I am running pytubefix 5.7 with Python 3.9.

Around one hour ago a new issue arised.

While trying to download audio files (itag = 140), this error message is generated:

`[91mget_throttling_function_name: could not find match for multiple[0m   <class 'pytubefix.exceptions.RegexMatchError'>`

Seems Youtube changed something in their side.

**Comment by giklepach** [comment]
Same problem

**Comment by buffalobill571** [comment]
Same issue, urgent fix needed

**Comment by NannoSilver** [comment]
> ```python
> function_patterns = [
>     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
>     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
>     # var Bpa = [iha];
>     # ...
>     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
>     # Bpa.length || iha("")) }};
>     # In the above case, `iha` is the relevant function name
>     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ]
> ```

I am testing this fix.
Have to implement it at `cipher.py`, line 98.
Seems it works!

**Comment by buffalobill571** [comment]
"

> > ```python
> > function_patterns = [
> >     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
> >     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
> >     # var Bpa = [iha];
> >     # ...
> >     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
> >     # Bpa.length || iha("")) }};
> >     # In the above case, `iha` is the relevant function name
> >     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> >     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
> >     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> > ]
> > ```
> 
> I am testing this fix. Have to implement it at `cipher.py`, line 98. Seems it works!

Huge thanks @NannoSilver, you are true GOAT!!!!

**Comment by zhaohany** [comment]
> ```python
>     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ```

Same issue, this works

**Comment by morrischoga** [comment]
> ```python
> function_patterns = [
>     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
>     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
>     # var Bpa = [iha];
>     # ...
>     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
>     # Bpa.length || iha("")) }};
>     # In the above case, `iha` is the relevant function name
>     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ]
> ```

This worked for me

**Comment by CureSaba** [comment]
I still got error
```

---------------------------------------------------------------------------
RegexMatchError                           Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/pytubefix/__main__.py in fmt_streams(self)
    242         try:
--> 243             extract.apply_signature(stream_manifest, self.vid_info, self.js)
    244         except exceptions.ExtractError:

/usr/local/lib/python3.10/dist-packages/pytubefix/extract.py in apply_signature(stream_manifest, vid_info, js)
    414     """
--> 415     cipher = Cipher(js=js)
    416     discovered_n = dict()

/usr/local/lib/python3.10/dist-packages/pytubefix/cipher.py in __init__(self, js)
     24         self.signature_function_name = get_initial_function_name(js)
---> 25         self.throttling_function_name = get_throttling_function_name(js)
     26 

/usr/local/lib/python3.10/dist-packages/pytubefix/cipher.py in get_throttling_function_name(js)
    129 
--> 130     raise RegexMatchError(
    131         caller="get_throttling_function_name", pattern="multiple"

RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

RegexMatchError                           Traceback (most recent call last)
<ipython-input-3-b5305a793b26> in <cell line: 3>()
      1 from pytubefix import YouTube
      2 yt = YouTube(input("URL: "))
----> 3 print(yt.streams.get_highest_resolution().url)

/usr/local/lib/python3.10/dist-packages/pytubefix/__main__.py in streams(self)
    495         """
    496         self.check_availability()
--> 497         return StreamQuery(self.fmt_streams)
    498 
    499     @property

/usr/local/lib/python3.10/dist-packages/pytubefix/__main__.py in fmt_streams(self)
    248             pytubefix.__js__ = None
    249             pytubefix.__js_url__ = None
--> 250             extract.apply_signature(stream_manifest, self.vid_info, self.js)
    251 
    252         # build instances of :class:`Stream <Stream>`

/usr/local/lib/python3.10/dist-packages/pytubefix/extract.py in apply_signature(stream_manifest, vid_info, js)
    413 
    414     """
--> 415     cipher = Cipher(js=js)
    416     discovered_n = dict()
    417     for i, stream in enumerate(stream_manifest):

/usr/local/lib/python3.10/dist-packages/pytubefix/cipher.py in __init__(self, js)
     23     def __init__(self, js: str):
     24         self.signature_function_name = get_initial_function_name(js)
---> 25         self.throttling_function_name = get_throttling_function_name(js)
     26 
     27         self.calculated_n = None

/usr/local/lib/python3.10/dist-packages/pytubefix/cipher.py in get_throttling_function_name(js)
    128                     return array[int(idx)]
    129 
--> 130     raise RegexMatchError(
    131         caller="get_throttling_function_name", pattern="multiple"
    132     )

RegexMatchError: get_throttling_function_name: could not find match for multiple

```

**Comment by thisguyshouldworkforus** [comment]
> > ```python
> > function_patterns = [
> >     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
> >     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
> >     # var Bpa = [iha];
> >     # ...
> >     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
> >     # Bpa.length || iha("")) }};
> >     # In the above case, `iha` is the relevant function name
> >     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> >     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
> >     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> > ]
> > ```
> 
> This worked for me

This fixed it for me too ...

**Comment by ablackoff** [comment]
Same problem

**Comment by rizametovd** [comment]
Same problem

**Comment by yannickErp** [comment]
> try pip install pytubefix==5.8rc1 and tell me if it's working normally

Working fine for me! @JuanBindez

**Comment by thisguyshouldworkforus** [comment]
> try pip install pytubefix==5.8rc1 and tell me if it's working normally

This appears to have resolved the original issue of `pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`, however on the `5.8rc1` version I am now getting this (new?) error:

```python
Traceback (most recent call last):
  File "/opt/projects/mytube/./newsgetter.py", line 226, in <module>
    main()
  File "/opt/projects/mytube/./newsgetter.py", line 86, in main
    TITLE = str(yt.title).strip()
                ^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 539, in title
    self._author = self.vid_info.get("videoDetails", {}).get(
                   ^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 316, in vid_info
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 567, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 493, in _call_api
    del query['key']
        ~~~~~^^^^^^^
KeyError: 'key'
```

**Comment by JuanBindez** [comment]
> > try pip install pytubefix==5.8rc1 and tell me if it's working normally
> 
> This appears to have resolved the original issue of `pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`, however on the `5.8rc1` version I am now getting this (new?) error:
> 
> ```python
> Traceback (most recent call last):
>   File "/opt/projects/mytube/./newsgetter.py", line 226, in <module>
>     main()
>   File "/opt/projects/mytube/./newsgetter.py", line 86, in main
>     TITLE = str(yt.title).strip()
>                 ^^^^^^^^
>   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 539, in title
>     self._author = self.vid_info.get("videoDetails", {}).get(
>                    ^^^^^^^^^^^^^
>   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 316, in vid_info
>     innertube_response = innertube.player(self.video_id)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 567, in player
>     return self._call_api(endpoint, query, self.base_data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 493, in _call_api
>     del query['key']
>         ~~~~~^^^^^^^
> KeyError: 'key'
> ```

try pytubefix==6.1.1

**Comment by thisguyshouldworkforus** [comment]
> > > try pip install pytubefix==5.8rc1 and tell me if it's working normally
> > 
> > 
> > This appears to have resolved the original issue of `pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`, however on the `5.8rc1` version I am now getting this (new?) error:
> > ```python
> > Traceback (most recent call last):
> >   File "/opt/projects/mytube/./newsgetter.py", line 226, in <module>
> >     main()
> >   File "/opt/projects/mytube/./newsgetter.py", line 86, in main
> >     TITLE = str(yt.title).strip()
> >                 ^^^^^^^^
> >   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 539, in title
> >     self._author = self.vid_info.get("videoDetails", {}).get(
> >                    ^^^^^^^^^^^^^
> >   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 316, in vid_info
> >     innertube_response = innertube.player(self.video_id)
> >                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 567, in player
> >     return self._call_api(endpoint, query, self.base_data)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/innertube.py", line 493, in _call_api
> >     del query['key']
> >         ~~~~~^^^^^^^
> > KeyError: 'key'
> > ```
> 
> try pytubefix==6.1.1

That fixed it. Thank you, Sir!
